# New ports collection makefile for:	texlive-context-mathsets
# Date created:		13/03/2010 04:21:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	context-mathsets
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Set notation in ConTeXt.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
