# New ports collection makefile for:	texlive-plain
# Date created:		26/01/2009 16:02:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	plain
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The Plain TeX format.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
