# New ports collection makefile for:	texlive-esint
# Date created:		26/01/2009 16:07:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	esint
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extended set of integrals for Computer Modern.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
