# New ports collection makefile for:	texlive-gmdoc
# Date created:		26/01/2009 16:08:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	gmdoc
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Documentation of LaTeX packages.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
