# $FreeBSD$

PORTNAME=	Asana-Math
PORTVERSION=	20140509
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A font to typeset maths in Xe(La)TeX and Lua(La)TeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
