# New ports collection makefile for:	texlive-etex
# Date created:		13/03/2010 04:19:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	etex
PORTVERSION=	20110213
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	An extended version of TeX, from the NTS project.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
