# New ports collection makefile for:	texlive-ec
# Date created:		13/03/2010 04:34:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ec
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Computer modern fonts in T1 and TS1 encodings.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
