# New ports collection makefile for:	texlive-latexmp
# Date created:		13/03/2010 04:22:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	latexmp
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Interface for LaTeX-based typesetting in MetaPost

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
