# $FreeBSD$

PORTNAME=	latexdemo
PORTVERSION=	20140627
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Demonstrate LaTeX code with its resulting output.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
