# New ports collection makefile for:	texlive-gnu-freefont
# Date created:		13/03/2010 04:26:55
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	gnu-freefont
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A Unicode font, with rather wide coverage.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
