# $FreeBSD$

PORTNAME=	gnuplottex
PORTVERSION=	20121010
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Embed Gnuplot commands in LaTeX documents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
