# New ports collection makefile for:	texlive-preprint
# Date created:		26/01/2009 16:08:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	preprint
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A bundle of packages provided "as is".

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
