# $FreeBSD$

PORTNAME=	caladea
PORTVERSION=	20140821
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for the Caladea family of fonts

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
