# New ports collection makefile for:	texlive-powerdot
# Date created:		26/01/2009 16:10:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	powerdot
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A presentation class.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
