# New ports collection makefile for:	texlive-storebox
# Date created:		09/24/2011 05:03:13
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	storebox
PORTVERSION=	20111222
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Storing information for reuse.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
