# New ports collection makefile for:	texlive-mathexam
# Date created:		13/03/2010 04:44:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mathexam
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Package for typesetting exams.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
