# New ports collection makefile for:	texlive-spotcolor
# Date created:		13/03/2010 04:49:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	spotcolor
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Spot colours for pdfLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
