# New ports collection makefile for:	texlive-de-macro
# Date created:		13/03/2010 04:23:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	de-macro
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Expand private macros in a document.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
