# New ports collection makefile for:	texlive-fontwrap
# Date created:		13/03/2010 05:00:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fontwrap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Bind fonts to specific unicode blocks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
