# New ports collection makefile for:	texlive-fbs
# Date created:		26/01/2009 16:03:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fbs
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	BibTeX style for Frontiers in Bioscience.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
