# $FreeBSD$

PORTNAME=	multidef
PORTVERSION=	20160421
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Quickly define several similar macros

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
