# $FreeBSD$

PORTNAME=	luatexbase
PORTVERSION=	20110522
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Basic resource management for LuaTeX code.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
