# New ports collection makefile for:	texlive-ebsthesis
# Date created:		26/01/2009 16:11:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ebsthesis
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typesetting theses for economics

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
