# New ports collection makefile for:	texlive-jmn
# Date created:		26/01/2009 16:03:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	jmn
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The jmn package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
