# $FreeBSD$

PORTNAME=	lisp-on-tex
PORTVERSION=	20140713
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Execute LISP code in a LaTeX document.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
