# $FreeBSD$

PORTNAME=	lisp-on-tex
PORTVERSION=	20130305
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Execute LISP code in a LaTeX document.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
