# $FreeBSD$

PORTNAME=	hf-tikz
PORTVERSION=	20130115
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A simple way to highlight formulas and formula parts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
