# $FreeBSD$

PORTNAME=	pst-pulley
PORTVERSION=	20120119
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Plot pulleys, using pstricks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
