# New ports collection makefile for:	texlive-spanglish
# Date created:		01/08/2011 17:05:02
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	spanglish
PORTVERSION=	20110109
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Simplified Spanish support for Babel.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
