# New ports collection makefile for:	texlive-apa
# Date created:		13/03/2010 04:58:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	apa
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	American Psychological Association format.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
