# $FreeBSD$

PORTNAME=	pbibtex-base
PORTVERSION=	20160510
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bibliography styles and miscellaneous files for pBibTeX

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
