# $FreeBSD$

PORTNAME=	koma-script-sfs
PORTVERSION=	20120426
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Koma-script letter class option for Finnish.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
