# New ports collection makefile for:	texlive-HA-prosper
# Date created:		26/01/2009 16:06:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	HA-prosper
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The HA-prosper package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
