# New ports collection makefile for:	texlive-excludeonly
# Date created:		13/03/2010 04:42:13
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	excludeonly
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Prevent files being \include-ed.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
