# New ports collection makefile for:	texlive-facsimile
# Date created:		13/03/2010 04:42:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	facsimile
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Document class for preparing faxes.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
