# New ports collection makefile for:	texlive-galois
# Date created:		13/03/2010 05:00:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	galois
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset Galois connections.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
