# New ports collection makefile for:	texlive-cite
# Date created:		26/01/2009 16:10:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cite
PORTREVISION=	4
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Improved citation handling in LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
