# New ports collection makefile for:	texlive-compactbib
# Date created:		13/03/2010 04:23:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	compactbib
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Multiple thebibliography environments.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
