# New ports collection makefile for:	texlive-textpos
# Date created:		13/03/2010 04:50:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	textpos
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Place boxes at arbitrary positions on the LaTeX page.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
