# New ports collection makefile for:	texlive-tikzorbital
# Date created:		12/19/2012 05:04:29
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	tikzorbital
PORTVERSION=	20121218
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Atomic and molecular orbitals using TiKZ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
