# $FreeBSD$

PORTNAME=	typeoutfileinfo
PORTVERSION=	20120929
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Display class/package/file information.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
