# New ports collection makefile for:	texlive-feynmf
# Date created:		13/03/2010 04:22:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	feynmf
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros and fonts for creating Feynman (and other) diagrams.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
