# $FreeBSD$

PORTNAME=	repeatindex
PORTVERSION=	20111017
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Repeat items in an index after a page or column break

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
