# $FreeBSD$

PORTNAME=	cntformats
PORTVERSION=	20140721
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A different way to read counters.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
