# $FreeBSD$

PORTNAME=	reflectgraphics
PORTVERSION=	20131119
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Techniques for reflecting graphics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
