# New ports collection makefile for:	texlive-here
# Date created:		13/03/2010 04:52:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	here
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Emulation of obsolete package for "here" floats.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
