# New ports collection makefile for:	texlive-lhcyr
# Date created:		26/01/2009 16:05:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lhcyr
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A non-standard Cyrillic input scheme.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
