# $FreeBSD$

PORTNAME=	phonrule
PORTVERSION=	20151124
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset linear phonological rules

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
