# New ports collection makefile for:	texlive-bera
# Date created:		26/01/2009 16:04:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bera
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Bera fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
