# New ports collection makefile for:	texlive-tree-dvips
# Date created:		03/20/2011 04:47:29
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	tree-dvips
PORTVERSION=	20110318
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Trees and other linguists' macros.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
