# $FreeBSD$

PORTNAME=	lua-visual-debug
PORTVERSION=	20120410
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Visual debugging with LuaLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
