# New ports collection makefile for:	texlive-skull
# Date created:		13/03/2010 04:29:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	skull
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A font to draw a skull.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
