# $FreeBSD$

PORTNAME=	subfigmat
PORTVERSION=	20101105
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Automates layout when using the subfigure package.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
