# New ports collection makefile for:	texlive-cmarrows
# Date created:		13/03/2010 04:21:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cmarrows
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	MetaPost arrows and braces in the Computer Modern style.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
