# New ports collection makefile for:	texlive-regexpatch
# Date created:		04/17/2012 05:03:22
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	regexpatch
PORTVERSION=	20120417
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	High level patching of commands.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
