# New ports collection makefile for:	texlive-bguq
# Date created:		08/02/2012 12:21:46
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	bguq
PORTVERSION=	20120815
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Improved quantifier stroke for Begriffsschrift packages.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
