# $FreeBSD$

PORTNAME=	sourcecodepro
PORTVERSION=	20150515
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use SourceCodePro with TeX(-alike) systems.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
