# New ports collection makefile for:	texlive-makeglos
# Date created:		26/01/2009 16:08:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	makeglos
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Include a glossary into a document.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
