# New ports collection makefile for:	texlive-numericplots
# Date created:		09/21/2010 11:44:27
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	numericplots
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Plot numeric data (including Matlab export) using PSTricks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
