# New ports collection makefile for:	texlive-cdpbundl
# Date created:		13/03/2010 04:39:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cdpbundl
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Business letters in the Italian style.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
