# New ports collection makefile for:	texlive-parallel
# Date created:		26/01/2009 16:05:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	parallel
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset parallel texts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
