# New ports collection makefile for:	texlive-register
# Date created:		13/03/2010 04:48:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	register
PORTVERSION=	20110121
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset programmable elements in digital hardware (registers).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
