# New ports collection makefile for:	texlive-foekfont
# Date created:		26/01/2009 16:04:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	foekfont
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The title font of the Mads Føk magazine.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
