# New ports collection makefile for:	texlive-pgf
# Date created:		13/03/2010 04:52:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pgf
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create PostScript and PDF graphics in TeX.

RUN_DEPENDS=	${LOCALBASE}/share/texmf-dist/tex/generic/xkeyval/xkeyval.tex:${PORTSDIR}/print/texlive-xkeyval

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
