# New ports collection makefile for:	texlive-computational-complexity
# Date created:		13/03/2010 05:00:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	computational-complexity
PORTVERSION=	20120509
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Class for the journal Computational Complexity.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
