# New ports collection makefile for:	texlive-poster-mac
# Date created:		09/21/2010 11:50:28
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	poster-mac
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Make posters and banners with TeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
