# New ports collection makefile for:	texlive-xypdf
# Date created:		04/11/2010 14:22:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xypdf
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	PDF output for XYpic.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
