# New ports collection makefile for:	texlive-pst-ob3d
# Date created:		26/01/2009 16:11:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-ob3d
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Three dimensional objects using PSTricks.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
