# New ports collection makefile for:	texlive-harvardkyoto
# Date created:		13/03/2010 05:00:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	harvardkyoto
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	XeTeX input map for Unicode Devanagari.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
