# New ports collection makefile for:	texlive-xetex-devanagari
# Date created:		05/10/2011 05:10:19
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	xetex-devanagari
PORTVERSION=	20110726
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	XeTeX input map for Unicode Devanagari.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
