# New ports collection makefile for:	texlive-nrc
# Date created:		13/03/2010 04:58:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nrc
PORTVERSION=	20121106
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Class for the NRC technical journals.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
