# $FreeBSD$

PORTNAME=	eqnarray
PORTVERSION=	20101203
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	More generalised equation arrays with numbering.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
