# New ports collection makefile for:	texlive-papercdcase
# Date created:		13/03/2010 04:46:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	papercdcase
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Origami-style folding paper CD case.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
