# New ports collection makefile for:	texlive-nfssext-cfr
# Date created:		13/03/2010 04:46:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nfssext-cfr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extensions to the LaTeX NFSS.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
