# $FreeBSD$

PORTNAME=	scsnowman
PORTVERSION=	20170123
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Snowman variants using TikZ

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
