# New ports collection makefile for:	texlive-pictex
# Date created:		13/03/2010 04:52:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pictex
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Picture drawing macros for TeX and LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
