# New ports collection makefile for:	texlive-ifplatform
# Date created:		13/03/2010 04:43:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ifplatform
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Conditionals to test which platform is being used.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
