# $FreeBSD$

PORTNAME=	ruhyphen
PORTVERSION=	20110116
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Russian hyphenation.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
