# New ports collection makefile for:	texlive-selectp
# Date created:		13/03/2010 04:48:40
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	selectp
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Select pages to be output.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
