# New ports collection makefile for:	texlive-lettre
# Date created:		13/03/2010 04:44:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lettre
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Letters and faxes in French.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
