# New ports collection makefile for:	texlive-decimal
# Date created:		13/03/2010 04:40:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	decimal
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX package for the English raised decimal point.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
