# New ports collection makefile for:	texlive-emulateapj
# Date created:		13/03/2010 04:41:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	emulateapj
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Produce output similar to that of APJ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
