# New ports collection makefile for:	texlive-epigram
# Date created:		11/23/2010 04:43:28
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	epigram
PORTVERSION=	20101123
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Display short quotations.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
