# New ports collection makefile for:	texlive-pst-slpe
# Date created:		13/03/2010 04:57:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-slpe
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Sophisticated colour gradients.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
