# New ports collection makefile for:	texlive-pst-slpe
# Date created:		26/01/2009 16:11:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-slpe
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Sophisticated colour gradients.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
