# New ports collection makefile for:	texlive-bclogo
# Date created:		13/03/2010 04:55:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bclogo
PORTVERSION=	20110802
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Creating colourful boxes with logos.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
