# $FreeBSD$

PORTNAME=	pst-solides3d
PORTVERSION=	20140908
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw perspective views of 3D solids.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
