# New ports collection makefile for:	texlive-nextpage
# Date created:		13/03/2010 04:46:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nextpage
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generalisations of the page advance commands.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
