# $FreeBSD$

PORTNAME=	pst-spirograph
PORTVERSION=	20140821
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Drawing hypotrochoids with a spirograph.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
