# New ports collection makefile for:	texlive-titlefoot
# Date created:		13/03/2010 04:50:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	titlefoot
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Add special material to footer of title page.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
