# New ports collection makefile for:	texlive-flippdf
# Date created:		26/01/2009 16:07:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	flippdf
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Horizontal flipping of pages with pdfLaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
