# New ports collection makefile for:	texlive-philex
# Date created:		13/03/2010 04:47:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	philex
PORTVERSION=	20120924
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Cross references for named and numbered environments.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
