# $FreeBSD$

PORTNAME=	pas-cv
PORTVERSION=	20131128
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Flexible typesetting of Curricula Vitae.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
