# New ports collection makefile for:	texlive-parselines
# Date created:		10/26/2010 04:56:06
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	parselines
PORTVERSION=	20101119
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Apply a macro to each line of an environment.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
