# New ports collection makefile for:	texlive-emulateapj
# Date created:		26/01/2009 16:07:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	emulateapj
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Produce output similar to that of APJ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
