# $FreeBSD$

PORTNAME=	nicefilelist
PORTVERSION=	20121214
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Provide \listfiles alignment.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
