# New ports collection makefile for:	texlive-fancyref
# Date created:		13/03/2010 04:53:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fancyref
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A LaTeX package for fancy cross-referencing.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
