# New ports collection makefile for:	texlive-program
# Date created:		26/01/2009 16:08:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	program
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typesetting programs and algorithms.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
