# $FreeBSD$

PORTNAME=	sanitize-umlaut
PORTVERSION=	20160612
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	sanitize umlauts for MakeIndex and pdfLaTeX

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
