# New ports collection makefile for:	texlive-dvipsconfig
# Date created:		26/01/2009 16:11:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dvipsconfig
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Collection of dvips PostScript headers.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
