# New ports collection makefile for:	texlive-pgfkeyx
# Date created:		04/25/2012 04:54:34
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	pgfkeyx
PORTVERSION=	20120425
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extended and more robust version of pgfkeys.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
