# $FreeBSD$

PORTNAME=	zwpagelayout
PORTVERSION=	20130116
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Page layout and crop-marks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
