# New ports collection makefile for:	texlive-zwpagelayout
# Date created:		26/01/2009 16:10:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	zwpagelayout
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Page layout and crop-marks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
