# $FreeBSD$

PORTNAME=	pict2e
PORTVERSION=	20140114
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	New implementation of picture commands.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
