# New ports collection makefile for:	texlive-xgreek
# Date created:		13/03/2010 04:36:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xgreek
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	XeLaTeX package for typesetting Greek language documents (beta release).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
