# New ports collection makefile for:	texlive-ted
# Date created:		13/03/2010 04:50:01
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ted
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A (primitive) token list editor.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
