# New ports collection makefile for:	texlive-disser
# Date created:		13/03/2010 04:34:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	disser
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Class and templates for typesetting dissertations in Russian.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
