# New ports collection makefile for:	texlive-snapshot
# Date created:		13/03/2010 04:49:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	snapshot
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	List the external dependencies of a LaTeX document.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
