# New ports collection makefile for:	texlive-concepts
# Date created:		12/10/2012 06:21:07
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	concepts
PORTVERSION=	20121229
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Keeping track of formal 'concepts' for a particular field.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
