# New ports collection makefile for:	texlive-texilikecover
# Date created:		26/01/2009 16:09:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	texilikecover
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The texilikecover package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
