# $FreeBSD$

PORTNAME=	l3build
PORTVERSION=	20150929
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A testing and building system for (La)TeX

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
