# New ports collection makefile for:	texlive-xgreek
# Date created:		26/01/2009 16:06:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xgreek
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	XeLaTeX package for typesetting Greek language documents (beta release).

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
