# New ports collection makefile for:	texlive-dviincl
# Date created:		26/01/2009 16:03:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dviincl
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Include a DVI page into MetaPost output.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
