# New ports collection makefile for:	texlive-xskak
# Date created:		13/03/2010 04:31:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xskak
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	An extension to the skak package for chess typesetting.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
