# New ports collection makefile for:	texlive-hf-tikz
# Date created:		08/21/2012 05:00:52
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	hf-tikz
PORTVERSION=	20121219
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A simple way to highlight formulas and formula parts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
