# New ports collection makefile for:	texlive-mft
# Date created:		26/01/2009 16:03:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mft
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The mft package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
