# New ports collection makefile for:	texlive-colortbl
# Date created:		13/03/2010 04:20:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	colortbl
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Add colour to LaTeX tables.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
