# $FreeBSD$

PORTNAME=	urlbst
PORTVERSION=	20120515
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Web support for BibTeX.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
