# New ports collection makefile for:	texlive-cooking
# Date created:		26/01/2009 16:07:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cooking
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset recipes.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
