# New ports collection makefile for:	texlive-iwona
# Date created:		26/01/2009 16:03:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	iwona
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A two-element sans-serif font.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
