# New ports collection makefile for:	texlive-easy-todo
# Date created:		01/15/2011 04:53:30
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	easy-todo
PORTVERSION=	20110124
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	To-do notes in a document.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
