# New ports collection makefile for:	texlive-ifxetex
# Date created:		26/01/2009 16:02:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ifxetex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Am I running under XeTeX?

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
