# $FreeBSD$

PORTNAME=	ling-macros
PORTVERSION=	20161016
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros for typesetting formal linguistics

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
