# New ports collection makefile for:	texlive-tcldoc
# Date created:		26/01/2009 16:09:34
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tcldoc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The tcldoc package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
