# New ports collection makefile for:	texlive-edmargin
# Date created:		26/01/2009 16:07:34
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	edmargin
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Multiple series of endnotes for critical editions.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
