# New ports collection makefile for:	texlive-context-chromato
# Date created:		26/01/2009 16:03:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	context-chromato
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	ConTeXt macros for chromatograms.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
