# New ports collection makefile for:	texlive-tap
# Date created:		26/01/2009 16:06:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	TeX macros for typesetting complex tables.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
