# New ports collection makefile for:	texlive-pbox
# Date created:		26/01/2009 16:08:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pbox
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A variable-width \parbox command.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
