# New ports collection makefile for:	texlive-tools
# Date created:		26/01/2009 16:03:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tools
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The LaTeX standard tools bundle.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
