# New ports collection makefile for:	texlive-cclicenses
# Date created:		26/01/2009 16:06:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cclicenses
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The cclicenses package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
