# New ports collection makefile for:	texlive-lps
# Date created:		26/01/2009 16:11:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lps
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Class for "Logic and Philosophy of Science".

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
