# New ports collection makefile for:	texlive-cmap
# Date created:		13/03/2010 04:53:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cmap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make PDF files searchable and copyable.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
