# New ports collection makefile for:	texlive-chemarrow
# Date created:		26/01/2009 16:11:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	chemarrow
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Arrows for use in chemistry.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
