# New ports collection makefile for:	texlive-spot
# Date created:		09/23/2010 06:00:52
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	spot
PORTVERSION=	20110512
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Spotlight highlighting for Beamer.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
