# New ports collection makefile for:	texlive-aomart
# Date created:		01/08/2011 17:11:31
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	aomart
PORTVERSION=	20120820
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset articles for the Annals of Mathematics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
