# $FreeBSD$

PORTNAME=	librecaslon
PORTVERSION=	20130629
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Libre Caslon fonts, with LaTeX support.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
