# New ports collection makefile for:	texlive-formular
# Date created:		13/03/2010 04:42:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	formular
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create forms containing field for manual entry.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
