# New ports collection makefile for:	texlive-ucdavisthesis
# Date created:		13/03/2010 04:59:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ucdavisthesis
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A thesis/dissertation class for University of California Davis.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
