# New ports collection makefile for:	texlive-cmap
# Date created:		13/03/2010 04:53:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cmap
PORTVERSION=	20120523
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The cmap package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
