# $FreeBSD$

PORTNAME=	uptex-fonts
PORTVERSION=	20160515
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fonts for use with upTeX

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
