# New ports collection makefile for:	texlive-yplan
# Date created:		13/03/2010 04:51:50
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	yplan
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Daily planner type calendar.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
