# New ports collection makefile for:	texlive-sf298
# Date created:		13/03/2010 04:48:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sf298
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Standard form 298.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
