# New ports collection makefile for:	texlive-harvard
# Date created:		13/03/2010 04:23:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	harvard
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Harvard citation package for use with LaTeX 2e.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
