# New ports collection makefile for:	texlive-doublestroke
# Date created:		13/03/2010 04:26:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	doublestroke
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset mathematical double stroke symbols.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
