# $FreeBSD$

PORTNAME=	uassign
PORTVERSION=	20150926
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Environments and options for typesetting university assignments

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
