# New ports collection makefile for:	texlive-embrac
# Date created:		08/02/2012 12:37:04
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	embrac
PORTVERSION=	20120727
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Upright brackets in emphasised text.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
