# $FreeBSD$

PORTNAME=	pxjahyper
PORTVERSION=	20121212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Hyperref support for pLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
