# New ports collection makefile for:	texlive-pb-diagram
# Date created:		26/01/2009 16:10:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pb-diagram
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A commutative diagram package using LAMSTeX or Xy-pic fonts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
