# New ports collection makefile for:	texlive-apptools
# Date created:		12/02/2012 05:01:19
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	apptools
PORTVERSION=	20121201
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Tools for customising appendices.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
