# $FreeBSD$

PORTNAME=	luahyphenrules
PORTVERSION=	20161211
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Loading patterns in LuaLaTeX with language.dat

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
