# New ports collection makefile for:	texlive-biblatex-nature
# Date created:		13/03/2010 04:23:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	biblatex-nature
PORTVERSION=	20110302
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Biblatex support for Nature.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
