# $FreeBSD$

PORTNAME=	biblatex-nature
PORTVERSION=	20160312
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibLaTeX support for Nature

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
