# New ports collection makefile for:	texlive-nuc
# Date created:		05/01/2011 05:10:08
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	nuc
PORTVERSION=	20110430
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Notation for nuclear isotopes.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
