# New ports collection makefile for:	texlive-sfg
# Date created:		13/03/2010 05:00:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sfg
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw signal flow graphs.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
