# New ports collection makefile for:	texlive-symbol
# Date created:		26/01/2009 16:04:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	symbol
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The symbol package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
