# New ports collection makefile for:	texlive-musixtex-fonts
# Date created:		11/11/2011 05:10:56
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	musixtex-fonts
PORTVERSION=	20111106
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fonts used by MusixTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
