# New ports collection makefile for:	texlive-breakurl
# Date created:		26/01/2009 16:06:53
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	breakurl
PORTREVISION=	11
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Line-breakable \url-like links in hyperref when compiling via dvips/ps2pdf.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
