# $FreeBSD$

PORTNAME=	pgfgantt
PORTVERSION=	20120127
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Gantt charts with TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
