# New ports collection makefile for:	texlive-showexpl
# Date created:		13/03/2010 04:48:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	showexpl
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typesetting LaTeX source code.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
