# New ports collection makefile for:	texlive-etex-pkg
# Date created:		26/01/2009 16:02:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	etex-pkg
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	E-TeX support package.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
