# New ports collection makefile for:	texlive-sudokubundle
# Date created:		26/01/2009 16:05:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sudokubundle
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A set of sudoku-related packages.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
