# New ports collection makefile for:	texlive-thumb
# Date created:		26/01/2009 16:09:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	thumb
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Thumb marks in documents.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
