# $FreeBSD$

PORTNAME=	numberedblock
PORTVERSION=	20140307
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Print a block of code, with unique index number.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
