# New ports collection makefile for:	texlive-svn-multi
# Date created:		26/01/2009 16:09:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	svn-multi
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Subversion keywords in multi-file LaTeX documents

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
