# New ports collection makefile for:	texlive-newspaper
# Date created:		26/01/2009 16:08:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newspaper
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset newsletters to resemble newspapers.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
