# New ports collection makefile for:	texlive-ionumbers
# Date created:		26/01/2009 16:10:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ionumbers
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Restyle numbers in maths mode.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
