# $FreeBSD$

PORTNAME=	pst-ovl
PORTVERSION=	20140515
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create and manage graphical overlays.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
