# New ports collection makefile for:	texlive-foilhtml
# Date created:		13/03/2010 04:42:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	foilhtml
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Interface between foiltex and LaTeX2HTML.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
