# New ports collection makefile for:	texlive-arsclassica
# Date created:		13/03/2010 04:58:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	arsclassica
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A different view of the ClassicThesis package.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
