# New ports collection makefile for:	texlive-svn
# Date created:		26/01/2009 16:09:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	svn
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset Subversion keywords.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
