# New ports collection makefile for:	texlive-musictex
# Date created:		13/03/2010 04:55:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	musictex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typesetting music with TeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
