# New ports collection makefile for:	texlive-wnri
# Date created:		26/01/2009 16:06:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	wnri
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Ridgeway's fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
