# New ports collection makefile for:	texlive-sort-by-letters
# Date created:		26/01/2009 16:03:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sort-by-letters
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Bibliography styles for alphabetic sorting.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
