# New ports collection makefile for:	texlive-needspace
# Date created:		13/03/2010 04:46:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	needspace
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Insert pagebreak if not enough space.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
