# New ports collection makefile for:	texlive-kluwer
# Date created:		13/03/2010 04:58:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	kluwer
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The kluwer package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
