# $FreeBSD$

PORTNAME=	archaeologie
PORTVERSION=	20151108
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Citation-style which covers rules of the German Archaeology Institute

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
