# New ports collection makefile for:	texlive-dblfloatfix
# Date created:		13/03/2010 04:40:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dblfloatfix
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fixes for twocolumn floats.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
