# $FreeBSD$

PORTNAME=	xepersian
PORTVERSION=	20160915
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Persian for LaTeX, using XeTeX

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
