# $FreeBSD$

PORTNAME=	fibeamer
PORTVERSION=	20151122
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Beamer theme for thesis defense presentations at Masaryk University (Brno, Czech Republic)

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
