# New ports collection makefile for:	texlive-psgo
# Date created:		13/03/2010 04:31:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	psgo
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset go diagrams with PSTricks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
