# New ports collection makefile for:	texlive-york-thesis
# Date created:		26/01/2009 16:11:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	york-thesis
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A thesis class file for York University, Toronto.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
