# New ports collection makefile for:	texlive-greek-inputenc
# Date created:		13/03/2010 04:36:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	greek-inputenc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Greek encoding support for inputenc.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
