# New ports collection makefile for:	texlive-cns
# Date created:		13/03/2010 04:33:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cns
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The cns package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
