# New ports collection makefile for:	texlive-complexity
# Date created:		26/01/2009 16:11:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	complexity
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Computational complexity class names.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
