# New ports collection makefile for:	texlive-xeindex
# Date created:		13/03/2010 05:00:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xeindex
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Automatic index generation for XeLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
