# New ports collection makefile for:	texlive-aspectratio
# Date created:		01/30/2012 04:42:57
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	aspectratio
PORTVERSION=	20120130
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Capital A and capital R ligature for Aspect Ratio.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
