# New ports collection makefile for:	texlive-limap
# Date created:		26/01/2009 16:08:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	limap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset maps and blocks according to the Information Mapping method.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
