# New ports collection makefile for:	texlive-refstyle
# Date created:		26/01/2009 16:09:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	refstyle
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Advanced formatting of cross references.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
