# New ports collection makefile for:	texlive-substr
# Date created:		13/03/2010 04:49:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	substr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Deal with substrings in strings.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
