# New ports collection makefile for:	texlive-tpic2pdftex
# Date created:		13/03/2010 04:24:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tpic2pdftex
PORTVERSION=	20100922
CATEGORIES=	print
DISTFILES=	# None

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use tpic commands in PDFTeX.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
