# New ports collection makefile for:	texlive-ted
# Date created:		26/01/2009 16:09:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ted
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A (primitive) token list editor.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
