# $FreeBSD$

PORTNAME=	cs
PORTVERSION=	20140509
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Czech/Slovak-tuned Computer Modern fonts.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
