# New ports collection makefile for:	texlive-doi
# Date created:		26/01/2009 16:07:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	doi
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create correct hyperlinks for DOI numbers.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
