# $FreeBSD$

PORTNAME=	babel-german
PORTVERSION=	20131216
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Babel support for documents written in German.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
