# New ports collection makefile for:	texlive-IEEEconf
# Date created:		13/03/2010 04:57:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	IEEEconf
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for IEEE conference proceedings.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
