# New ports collection makefile for:	texlive-extsizes
# Date created:		13/03/2010 04:53:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	extsizes
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extend the standard classes' size options.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
