# New ports collection makefile for:	texlive-anonchap
# Date created:		13/03/2010 04:38:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	anonchap
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Make chapters be typeset like sections.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
