# New ports collection makefile for:	texlive-pdfmarginpar
# Date created:		13/03/2010 04:47:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdfmarginpar
PORTVERSION=	20110510
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate marginpar-equivalent PDF annotations.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
