# $FreeBSD$

PORTNAME=	pdfmarginpar
PORTVERSION=	20110812
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate marginpar-equivalent PDF annotations.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
