# $FreeBSD$

PORTNAME=	scanpages
PORTVERSION=	20140115
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support importing and embellishing scanned documents.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
