# $FreeBSD$

PORTNAME=	pst-math
PORTVERSION=	20101025
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Enhancement of PostScript math operators to use with pstricks


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
