# $FreeBSD$

PORTNAME=	classics
PORTVERSION=	20130204
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Cite classic works.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
