# New ports collection makefile for:	texlive-nostarch
# Date created:		26/01/2009 16:11:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nostarch
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX class for No Starch Press.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
