# $FreeBSD$

PORTNAME=	logicpuzzle
PORTVERSION=	20140701
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset (grid-based) logic puzzles.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
