# New ports collection makefile for:	texlive-qsymbols
# Date created:		26/01/2009 16:09:01
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	qsymbols
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Maths symbol abbreviations.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
