# $FreeBSD$

PORTNAME=	smartdiagram
PORTVERSION=	20130406
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate diagrams from lists.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
