# New ports collection makefile for:	texlive-context-vim
# Date created:		26/01/2009 16:03:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	context-vim
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Generate Context syntax highlighting code from vim.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
