# New ports collection makefile for:	texlive-fnbreak
# Date created:		13/03/2010 04:42:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fnbreak
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Warn for split footnotes.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
