# $FreeBSD$

PORTNAME=	beamertheme-upenn-bc
PORTVERSION=	20130416
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Beamer themies for Boston College and the University of Pennsylvania.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
