# New ports collection makefile for:	texlive-context-french
# Date created:		13/03/2010 04:21:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	context-french
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for writing French in ConTeXt.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
