# $FreeBSD$

PORTNAME=	spelling
PORTVERSION=	20130214
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for spell-checking of LuaLaTeX documents.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
