# New ports collection makefile for:	texlive-cjhebrew
# Date created:		13/03/2010 04:36:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cjhebrew
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset Hebrew with LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
