# New ports collection makefile for:	texlive-libertineotf
# Date created:		04/12/2012 04:46:21
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	libertineotf
PORTVERSION=	20120412
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Linux Libertine fonts for use with lua(La)TeX and xe(La)TeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
