# New ports collection makefile for:	texlive-persian-bib
# Date created:		13/03/2010 04:33:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	persian-bib
PORTVERSION=	20110730
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Persian translations of classic BibTeX styles.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
