# New ports collection makefile for:	texlive-fixpdfmag
# Date created:		26/01/2009 16:10:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fixpdfmag
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Fix magnification in PDFTeX.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
