# New ports collection makefile for:	texlive-cursor
# Date created:		26/01/2009 16:07:13
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cursor
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw a cursor in an equation.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
