# New ports collection makefile for:	texlive-bibleref
# Date created:		13/03/2010 04:32:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bibleref
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Format bible citations.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
