# $FreeBSD$

PORTNAME=	schwalbe-chess
PORTVERSION=	20120505
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset the German chess magazine "Die Schwalbe"


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
