# $FreeBSD$

PORTNAME=	persian-hm-xbs
PORTVERSION=	20130403
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Persian fonts derived from X series 2.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
