# New ports collection makefile for:	texlive-pst-vowel
# Date created:		13/03/2010 04:57:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-vowel
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Enable arrows showing diphthongs on vowel charts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
