# $FreeBSD$

PORTNAME=	lollipop
PORTVERSION=	20140426
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	TeX made easy.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
