# New ports collection makefile for:	texlive-ocr-latex
# Date created:		13/03/2010 04:46:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ocr-latex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX support for ocr fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
