# New ports collection makefile for:	texlive-midnight
# Date created:		13/03/2010 04:31:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	midnight
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A set of useful macro tools.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
