# New ports collection makefile for:	texlive-image-gallery
# Date created:		13/03/2010 04:43:40
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	image-gallery
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create an overview of pictures from a digital camera or from other sources.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
