# New ports collection makefile for:	texlive-harvmac
# Date created:		13/03/2010 04:23:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	harvmac
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for scientific articles.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
