# $FreeBSD$

PORTNAME=	detlev-cm
PORTVERSION=	20131212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The detlev-cm package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
