# New ports collection makefile for:	texlive-play
# Date created:		26/01/2009 16:05:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	play
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset drama using LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
