# New ports collection makefile for:	texlive-ltablex
# Date created:		13/03/2010 04:44:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ltablex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Table package extensions.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
