# New ports collection makefile for:	texlive-showtags
# Date created:		11/06/2010 04:38:07
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	showtags
PORTVERSION=	20101106
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Print the tags of bibliography entries.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
