# New ports collection makefile for:	texlive-crosswrd
# Date created:		13/03/2010 04:31:03
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	crosswrd
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros for typesetting crossword puzzles.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
