# New ports collection makefile for:	texlive-exam
# Date created:		13/03/2010 04:42:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	exam
PORTVERSION=	20110524
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Package for typesetting exam scripts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
