# New ports collection makefile for:	texlive-ipaex
# Date created:		10/30/2011 04:47:59
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	ipaex
PORTVERSION=	20111122
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	IPA and IPAex fonts from Information-technology Promotion Agency, Japan.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
