# New ports collection makefile for:	texlive-inversepath
# Date created:		13/03/2010 04:43:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	inversepath
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Calculate inverse file paths.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
