# New ports collection makefile for:	texlive-curves
# Date created:		13/03/2010 04:52:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	curves
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Curves for LaTeX picture environment


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
