# New ports collection makefile for:	texlive-tablists
# Date created:		26/01/2009 16:09:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tablists
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Tabulated lists of short items.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
