# $FreeBSD$

PORTNAME=	denisbdoc
PORTVERSION=	20160611
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A personal dirty package for documenting packages

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
