# $FreeBSD$

PORTNAME=	smartref
PORTVERSION=	20101105
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extend LaTeX's \ref capability.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
