# New ports collection makefile for:	texlive-circuitikz
# Date created:		13/03/2010 04:52:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	circuitikz
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw electrical networks with TikZ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
