# New ports collection makefile for:	texlive-relsize
# Date created:		13/03/2010 04:48:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	relsize
PORTVERSION=	20101009
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Set the font size relative to the current font size.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
