# New ports collection makefile for:	texlive-moderntimeline
# Date created:		10/01/2011 05:00:29
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	moderntimeline
PORTVERSION=	20111117
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Timelines for use with moderncv.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
