# New ports collection makefile for:	texlive-classicthesis
# Date created:		26/01/2009 16:11:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	classicthesis
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A "classically styled" thesis package.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
