# New ports collection makefile for:	texlive-lcd
# Date created:		13/03/2010 04:44:06
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lcd
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Alphanumerical LCD-style displays.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
