# New ports collection makefile for:	texlive-tabularcalc
# Date created:		13/03/2010 04:49:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tabularcalc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Calculate formulas in a tabular environment.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
