# $FreeBSD$

PORTNAME=	emp
PORTVERSION=	20110811
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	"Encapsulate" MetaPost figures in a document.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
