# New ports collection makefile for:	texlive-knitting
# Date created:		13/03/2010 04:52:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	knitting
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Produce knitting charts, in Plain TeX or LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
