# New ports collection makefile for:	texlive-bangtex
# Date created:		13/03/2010 04:37:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bangtex
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Writing Bangla and Assamese with LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
