# New ports collection makefile for:	texlive-anyfontsize
# Date created:		13/03/2010 04:38:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	anyfontsize
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Select any font size in LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
