# New ports collection makefile for:	texlive-ordinalpt
# Date created:		13/03/2010 04:37:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ordinalpt
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Counters as ordinal numbers in Portuguese.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
