# New ports collection makefile for:	texlive-featpost
# Date created:		13/03/2010 04:22:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	featpost
PORTVERSION=	20120131
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	MetaPost macros for 3D.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
