# $FreeBSD$

PORTNAME=	seealso
PORTVERSION=	20140408
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The seealso package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
