# New ports collection makefile for:	texlive-unroman
# Date created:		26/01/2009 16:09:53
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	unroman
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Converting Roman numerals to Arabic numbers.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
