# New ports collection makefile for:	texlive-umich-thesis
# Date created:		13/03/2010 04:59:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	umich-thesis
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	University of Michigan Thesis LaTeX class.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
