# New ports collection makefile for:	texlive-jfontmaps
# Date created:		02/03/2012 04:51:09
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	jfontmaps
PORTVERSION=	20120602
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Font maps for Japanese fonts.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
