# New ports collection makefile for:	texlive-jfontmaps
# Date created:		02/03/2012 04:51:09
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	jfontmaps
PORTVERSION=	20120203
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The jfontmaps package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
