# New ports collection makefile for:	texlive-flashcards
# Date created:		13/03/2010 04:42:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	flashcards
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A class for typesetting flashcards.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
