# $FreeBSD$

PORTNAME=	brandeis-dissertation
PORTVERSION=	20131018
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The brandeis-dissertation package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
