# $FreeBSD$

PORTNAME=	rubik
PORTVERSION=	20140209
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Document Rubik cube configurations and rotation sequences.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
