# New ports collection makefile for:	texlive-cmsd
# Date created:		13/03/2010 04:39:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cmsd
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Interfaces to the CM Sans Serif Bold fonts.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
