# New ports collection makefile for:	texlive-musixps
# Date created:		26/01/2009 16:10:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	musixps
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The musixps package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
