# New ports collection makefile for:	texlive-bidi
# Date created:		26/01/2009 16:12:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bidi
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for bidirectional typesetting with XeLaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
