# $FreeBSD$

PORTNAME=	bidi
PORTVERSION=	20130405
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for bidirectional typesetting in plain TeX and LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
