# New ports collection makefile for:	texlive-guitar
# Date created:		26/01/2009 16:10:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	guitar
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Guitar chords and song texts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
