# New ports collection makefile for:	texlive-robustcommand
# Date created:		13/03/2010 04:48:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	robustcommand
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Declare robust command, with \newcommand checks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
