# New ports collection makefile for:	texlive-tengwarscript
# Date created:		13/03/2010 04:29:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tengwarscript
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX support for using Tengwar fonts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
