# New ports collection makefile for:	texlive-uwthesis
# Date created:		13/03/2010 04:59:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	uwthesis
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	University of Washington thesis class.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
