# New ports collection makefile for:	texlive-jurabib
# Date created:		13/03/2010 04:23:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	jurabib
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extended BibTeX citation support for the humanities and legal texts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
