# New ports collection makefile for:	texlive-kixfont
# Date created:		13/03/2010 04:27:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	kixfont
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A font for KIX codes.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
