# New ports collection makefile for:	texlive-inconsolata
# Date created:		13/03/2010 04:27:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	inconsolata
PORTVERSION=	20100914
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A monospaced font, with support files for use with TeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
