# $FreeBSD$

PORTNAME=	latex-git-log
PORTVERSION=	20130629
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset git log information.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
