# $FreeBSD$

PORTNAME=	enumitem-zref
PORTVERSION=	20110220
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extended references to items for enumitem package.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
