# New ports collection makefile for:	texlive-cell
# Date created:		13/03/2010 04:23:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cell
PORTVERSION=	20101216
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bibliography style for Cell.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
