# $FreeBSD$

PORTNAME=	accanthis
PORTVERSION=	20131107
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Accanthis fonts, with LaTeX support.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
