# New ports collection makefile for:	texlive-textopo
# Date created:		13/03/2010 05:00:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	textopo
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Annotated membrane protein topology plots.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
