# $FreeBSD$

PORTNAME=	bitpattern
PORTVERSION=	20151212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset bit pattern diagrams

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
