# $FreeBSD$

PORTNAME=	ijsra
PORTVERSION=	20160901
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX document class for the International Journal of Student Research in Archaeology

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
