# New ports collection makefile for:	texlive-pst-node
# Date created:		13/03/2010 04:57:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-node
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw connections using pstricks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
