# New ports collection makefile for:	texlive-cwpuzzle
# Date created:		26/01/2009 16:07:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cwpuzzle
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The cwpuzzle package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
