# New ports collection makefile for:	texlive-gnuplottex
# Date created:		13/03/2010 04:52:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	gnuplottex
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Embed Gnuplot commands in LaTeX documents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
