# New ports collection makefile for:	texlive-misc
# Date created:		13/03/2010 04:19:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	misc
PORTVERSION=	20111228
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The misc package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
