# New ports collection makefile for:	texlive-faktor
# Date created:		26/01/2009 16:10:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	faktor
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset quotient structures with LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
