# $FreeBSD$

PORTNAME=	jlreq
PORTVERSION=	20170209
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Japanese document class based on requirements for Japanese text layout

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
