# $FreeBSD$

PORTNAME=	exam-n
PORTVERSION=	20140506
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Exam class, focused on collaborative authoring.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
