# New ports collection makefile for:	texlive-footmisc
# Date created:		26/01/2009 16:07:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	footmisc
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A range of footnote options.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
