# $FreeBSD$

PORTNAME=	latexmk
PORTVERSION=	20131105
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fully automated LaTeX document generation.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
