# New ports collection makefile for:	texlive-tex-label
# Date created:		13/03/2010 04:50:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tex-label
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Place a classification on each page of a document


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
