# New ports collection makefile for:	texlive-nature
# Date created:		26/01/2009 16:11:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nature
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Prepare papers for the journal Nature.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
