# New ports collection makefile for:	texlive-antiqua
# Date created:		13/03/2010 04:25:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	antiqua
PORTVERSION=	20110329
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	URW Antiqua font pack for LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
