# New ports collection makefile for:	texlive-msuthesis
# Date created:		12/15/2010 05:04:57
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	msuthesis
PORTVERSION=	20101215
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The msuthesis package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
