# New ports collection makefile for:	texlive-euxm
# Date created:		26/01/2009 16:04:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	euxm
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The euxm package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
