# New ports collection makefile for:	texlive-dvipos
# Date created:		13/03/2010 04:24:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dvipos
PORTVERSION=	20100922
CATEGORIES=	print
DISTFILES=	# None

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The dvipos package

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
