# $FreeBSD$

PORTNAME=	bangorcsthesis
PORTVERSION=	20140819
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset a thesis at Bangor University.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
