# New ports collection makefile for:	texlive-elsevier-bib
# Date created:		13/03/2010 04:23:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	elsevier-bib
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibTeX styles to be used in Elsevier preprints.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
