# New ports collection makefile for:	texlive-kalender
# Date created:		26/01/2009 16:06:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	kalender
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create a calendar, in German.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
