# $FreeBSD$

PORTNAME=	pst-3dplot
PORTVERSION=	20120730
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw 3D objects in parallel projection, using PSTricks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
