# New ports collection makefile for:	texlive-underlin
# Date created:		26/01/2009 16:09:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	underlin
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Underlined running heads.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
