# New ports collection makefile for:	texlive-apl
# Date created:		26/01/2009 16:04:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	apl
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Fonts for typesetting APL programs.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
