# New ports collection makefile for:	texlive-blkarray
# Date created:		13/03/2010 04:39:01
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	blkarray
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extended array and tabular.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
