# New ports collection makefile for:	texlive-hvfloat
# Date created:		26/01/2009 16:08:06
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hvfloat
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Rotating caption and object of floats independently.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
