# New ports collection makefile for:	texlive-luainputenc
# Date created:		13/03/2010 04:54:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	luainputenc
PORTVERSION=	20101120
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Replacing inputenc for use in LuaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
