# New ports collection makefile for:	texlive-newsletr
# Date created:		13/03/2010 04:55:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newsletr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for making newsletters with Plain TeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
