# New ports collection makefile for:	texlive-catoptions
# Date created:		02/12/2011 04:52:19
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	catoptions
PORTVERSION=	20110806
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Preserving and recalling standard catcodes.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
