# $FreeBSD$

PORTNAME=	reledmac
PORTVERSION=	20151020
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset scholarly editions

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
