# New ports collection makefile for:	texlive-timing
# Date created:		26/01/2009 16:09:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	timing
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Fonts and macro package for drawing timing diagrams.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
