# New ports collection makefile for:	texlive-uni-wtal-ger
# Date created:		04/27/2011 04:40:27
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	uni-wtal-ger
PORTVERSION=	20110427
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The uni-wtal-ger package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
