# New ports collection makefile for:	texlive-bbding
# Date created:		26/01/2009 16:04:06
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bbding
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A symbol (dingbat) font and LaTeX macros for its use.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
