# New ports collection makefile for:	texlive-ed
# Date created:		26/01/2009 16:07:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ed
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Editorial Notes for LaTeX documents.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
