# New ports collection makefile for:	texlive-ametsoc
# Date created:		13/03/2010 04:58:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ametsoc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Official American Meteorological Society Latex Template.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
