# $FreeBSD$

PORTNAME=	cleveref
PORTVERSION=	20120926
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Intelligent cross-referencing.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
