# New ports collection makefile for:	texlive-commath
# Date created:		13/03/2010 04:54:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	commath
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Mathematics typesetting support.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
