# $FreeBSD$

PORTNAME=	tikzpfeile
PORTVERSION=	20120330
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw arrows using PGF/TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
