# New ports collection makefile for:	texlive-bbm
# Date created:		26/01/2009 16:04:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bbm
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	"Blackboard-style" cm fonts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
