# New ports collection makefile for:	texlive-abbr
# Date created:		26/01/2009 16:05:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	abbr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Simple macros supporting abreviations for Plain and LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
