# $FreeBSD$

PORTNAME=	xint
PORTVERSION=	20131129
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Expandable operations on long numbers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
