# $FreeBSD$

PORTNAME=	doctools
PORTVERSION=	20140629
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Tools for the documentation of LaTeX code.

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
