# New ports collection makefile for:	texlive-constants
# Date created:		13/03/2010 04:40:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	constants
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Automatic numbering of constants.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
