# $FreeBSD$

PORTNAME=	underoverlap
PORTVERSION=	20130204
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Position decorations over and under expressions.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
