# New ports collection makefile for:	texlive-namespc
# Date created:		26/01/2009 16:08:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	namespc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Rudimentary c++-like namespaces in LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
