# New ports collection makefile for:	texlive-acroterm
# Date created:		11/21/2010 04:49:00
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	acroterm
PORTVERSION=	20101121
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Manage and index acronyms and terms.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
