# New ports collection makefile for:	texlive-pst-stru
# Date created:		13/03/2010 04:57:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-stru
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Civil engineering diagrams, using pstricks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
