# New ports collection makefile for:	texlive-startex
# Date created:		26/01/2009 16:04:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	startex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	An XML-inspired format for student use.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
