# New ports collection makefile for:	texlive-rccol
# Date created:		13/03/2010 04:47:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	rccol
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Decimal-centered optionally rounded numbers in tabular.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
