# $FreeBSD$

PORTNAME=	apa6
PORTVERSION=	20130627
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Format documents in APA style (6th edition).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
