# $FreeBSD$

PORTNAME=	pgf-spectra
PORTVERSION=	20170119
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw continuous or discrete spectra using PGF/TikZ

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
