# $FreeBSD$

PORTNAME=	pxchfon
PORTVERSION=	20121212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Japanese font setup for pLaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
