# New ports collection makefile for:	texlive-pxchfon
# Date created:		12/14/2012 04:54:59
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	pxchfon
PORTVERSION=	20121212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Japanese font setup for pLaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
