# $FreeBSD$

PORTNAME=	babel-friulan
PORTVERSION=	20140418
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Babel/Polyglossia support for Friulan(Furlan).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
