# $FreeBSD$

PORTNAME=	proofread
PORTVERSION=	20150908
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Commands for inserting annotations

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
