# New ports collection makefile for:	texlive-ledmac
# Date created:		13/03/2010 04:32:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ledmac
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset scholarly editions in parallel texts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
