# $FreeBSD$

PORTNAME=	luaotfload
PORTVERSION=	20140105
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	OpenType 'loader' for Plain TeX and LaTeX.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
