# $FreeBSD$

PORTNAME=	bxjscls
PORTVERSION=	20160718
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Japanese document class collection for all major engines

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
