# New ports collection makefile for:	texlive-dramatist
# Date created:		26/01/2009 16:05:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dramatist
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset dramas, both in verse and in prose.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
