# New ports collection makefile for:	texlive-pdfscreen
# Date created:		13/03/2010 04:47:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdfscreen
PORTVERSION=	20120821
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support screen-based document design.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
