# New ports collection makefile for:	texlive-sidecap
# Date created:		26/01/2009 16:09:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sidecap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset captions sideways.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
