# $FreeBSD$

PORTNAME=	texdiff
PORTVERSION=	20120515
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Compare documents and produce tagged merge.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
