# $FreeBSD$

PORTNAME=	etoc
PORTVERSION=	20130225
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Easily customisable TOCs.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
