# $FreeBSD$

PORTNAME=	comfortaa
PORTVERSION=	20120828
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Sans serif font, with LaTeX support.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
