# New ports collection makefile for:	texlive-recycle
# Date created:		13/03/2010 04:29:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	recycle
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A font providing the "recyclable" logo.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
