# New ports collection makefile for:	texlive-hanging
# Date created:		26/01/2009 16:08:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hanging
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Hanging paragraphs.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
