# $FreeBSD$

PORTNAME=	crossrefware
PORTVERSION=	20141020
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Scripts for working with crossref.org.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
