# New ports collection makefile for:	texlive-hc
# Date created:		13/03/2010 04:43:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Replacement for the LaTeX classes.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
