# New ports collection makefile for:	texlive-burmese
# Date created:		13/03/2010 04:37:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	burmese
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Basic Support for Writing Burmese.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
