# $FreeBSD$

PORTNAME=	biblatex-chem
PORTVERSION=	20130128
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A set of biblatex implementations of chemistry-related bibliography styles.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
