# New ports collection makefile for:	texlive-logpap
# Date created:		26/01/2009 16:08:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	logpap
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Generate logarithmic graph paper with LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
