# New ports collection makefile for:	texlive-trfsigns
# Date created:		13/03/2010 04:50:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	trfsigns
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset transform signs.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
