# New ports collection makefile for:	texlive-libertine
# Date created:		09/28/2012 04:58:02
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	libertine
PORTVERSION=	20120927
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Simple use of Linux Libertine and Biolinum fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
