# $FreeBSD$

PORTNAME=	toptesi
PORTVERSION=	20151221
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bundle for typesetting multilanguage theses

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
