# $FreeBSD$

PORTNAME=	showdim
PORTVERSION=	20130124
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Variants on printing dimensions.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
