# $FreeBSD$

PORTNAME=	pst-perspective
PORTVERSION=	20140415
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw perspective views using pstricks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
