# $FreeBSD$

PORTNAME=	withargs
PORTVERSION=	20150908
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Ephemeral macro use

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
