# New ports collection makefile for:	texlive-xecolour
# Date created:		13/03/2010 05:00:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xecolour
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for colour in XeLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
