# New ports collection makefile for:	texlive-koma-moderncvclassic
# Date created:		10/25/2010 04:54:15
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	koma-moderncvclassic
PORTVERSION=	20120107
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Makes the style and command of moderncv (style classic) available for koma-classes and thus compatible with biblatex.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
