# $FreeBSD$

PORTNAME=	lualatex-math
PORTVERSION=	20160420
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fixes for mathematics-related LuaLaTeX issues

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
