# $FreeBSD$

PORTNAME=	fundus-calligra
PORTVERSION=	20120418
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for the calligra font in LaTeX documents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
