# New ports collection makefile for:	texlive-sdrt
# Date created:		13/03/2010 04:48:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sdrt
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for Segmented Discourse Representation Theory.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
