# New ports collection makefile for:	texlive-listings
# Date created:		26/01/2009 16:10:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	listings
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset source code listings using LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
