# New ports collection makefile for:	texlive-technics
# Date created:		13/03/2010 04:50:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	technics
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A package to format technical documents.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
