# New ports collection makefile for:	texlive-localloc
# Date created:		13/03/2010 04:44:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	localloc
PORTVERSION=	20110404
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros for localizing TeX register allocations.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
