# New ports collection makefile for:	texlive-sapthesis
# Date created:		09/17/2011 05:09:38
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	sapthesis
PORTVERSION=	20120310
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset theses for Sapienza-University, Rome.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
