# New ports collection makefile for:	texlive-jneurosci
# Date created:		13/03/2010 04:23:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	jneurosci
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibTeX style for the Journal of Neuroscience.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
