# New ports collection makefile for:	texlive-bbcard
# Date created:		13/03/2010 04:21:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bbcard
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bullshit bingo, calendar and baseball-score cards.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
