# $FreeBSD$

PORTNAME=	odsfile
PORTVERSION=	20120814
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Read OpenDocument Spreadsheet documents as LaTeX tables.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
