# New ports collection makefile for:	texlive-marginfix
# Date created:		09/21/2010 11:48:51
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	marginfix
PORTVERSION=	20111019
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Patch \marginpar to avoid overfull margins.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
