# New ports collection makefile for:	texlive-forloop
# Date created:		13/03/2010 04:42:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	forloop
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Iteration in LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
