# $FreeBSD$

PORTNAME=	umoline
PORTVERSION=	20100621
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Underline text allowing line breaking.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
