# New ports collection makefile for:	texlive-seqsplit
# Date created:		26/01/2009 16:09:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	seqsplit
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Split long sequences of characters in a neutral way.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
