# New ports collection makefile for:	texlive-changepage
# Date created:		13/03/2010 04:39:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	changepage
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Margin adjustment and detection of odd/even pages.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
