# $FreeBSD$

PORTNAME=	secdot
PORTVERSION=	20101026
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Section numbers with trailing dots.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
