# New ports collection makefile for:	texlive-crop
# Date created:		26/01/2009 16:10:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	crop
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for cropmarks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
