# $FreeBSD$

PORTNAME=	testhyphens
PORTVERSION=	20140914
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Testing hyphenation patterns


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
