# New ports collection makefile for:	texlive-uafthesis
# Date created:		04/27/2011 05:09:39
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	uafthesis
PORTVERSION=	20110427
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Document class for theses at University of Alaska Fairbanks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
