# $FreeBSD$

PORTNAME=	isonums
PORTVERSION=	20100610
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Display numbers in maths mode according to ISO 31-0.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
