# New ports collection makefile for:	texlive-biblatex
# Date created:		13/03/2010 04:23:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	biblatex
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Bibliographies in LaTeX using BibTeX for sorting only.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
