# $FreeBSD$

PORTNAME=	mdframed
PORTVERSION=	20120922
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Framed environments that can split at page boundaries.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
