# New ports collection makefile for:	texlive-listbib
# Date created:		13/03/2010 04:23:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	listbib
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Lists contents of BibTeX files.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
