# New ports collection makefile for:	texlive-eemeir
# Date created:		26/01/2009 16:07:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	eemeir
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Adjust the gender of words in a document.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
