# New ports collection makefile for:	texlive-envlab
# Date created:		26/01/2009 16:07:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	envlab
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Addresses on envelopes or mailing labels.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
