# New ports collection makefile for:	texlive-ifsym
# Date created:		13/03/2010 04:27:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ifsym
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of symbols.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
