# New ports collection makefile for:	texlive-tufte-latex
# Date created:		13/03/2010 04:52:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tufte-latex
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Document classes inspired by the work of Edward Tufte.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
