# New ports collection makefile for:	texlive-pdftex-def
# Date created:		26/01/2009 16:03:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdftex-def
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Colour and Graphics support for PDFTeX.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
