# New ports collection makefile for:	texlive-ifluatex
# Date created:		13/03/2010 04:19:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ifluatex
PORTREVISION=	3
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Provides the \ifluatex switch.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
