# $FreeBSD$

PORTNAME=	markdown
PORTVERSION=	20161209
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A package for converting and rendering markdown documents inside TeX

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
