# New ports collection makefile for:	texlive-topfloat
# Date created:		26/01/2009 16:09:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	topfloat
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Move floats to the top of the page.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
