# $FreeBSD$

PORTNAME=	xecjk
PORTVERSION=	20140625
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for CJK documents in XeLaTeX.

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
