# New ports collection makefile for:	texlive-pdfx
# Date created:		13/03/2010 04:47:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdfx
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	PDF/X-1a and PDF/A-1b support for pdfTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
