# New ports collection makefile for:	texlive-pst-optic
# Date created:		13/03/2010 04:57:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-optic
PORTVERSION=	20100914
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Drawing optics diagrams.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
