# $FreeBSD$

PORTNAME=	ocgx2
PORTVERSION=	20160325
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Drop-in replacement for the 'ocgx' package; adds support for dvips+ps2pdf, XeLaTeX, dvipdfmx

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
