# New ports collection makefile for:	texlive-miller
# Date created:		26/01/2009 16:11:53
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	miller
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset miller indices.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
