# New ports collection makefile for:	texlive-xelibertine
# Date created:		26/01/2009 16:12:03
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xelibertine
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Making the libertine font available in Xe(La)TeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
