# New ports collection makefile for:	texlive-pst-fr3d
# Date created:		26/01/2009 16:11:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-fr3d
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw 3-dimensional framed boxes using PSTricks.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
