# $FreeBSD$

PORTNAME=	fixltxhyph
PORTVERSION=	20120403
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Allow hyphenation of partially-emphasised substrings.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
