# New ports collection makefile for:	texlive-phonetic
# Date created:		26/01/2009 16:04:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	phonetic
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	MetaFont Phonetic fonts, based on Computer Modern.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
