# New ports collection makefile for:	texlive-phonetic
# Date created:		13/03/2010 04:28:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	phonetic
PORTVERSION=	20110330
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	MetaFont Phonetic fonts, based on Computer Modern.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
