# New ports collection makefile for:	texlive-drac
# Date created:		13/03/2010 04:40:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	drac
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Declare active character substitution, robustly.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
