# $FreeBSD$

PORTNAME=	euro
PORTVERSION=	20110425
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Provide Euro values for national currency amounts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
