# New ports collection makefile for:	texlive-tablor
# Date created:		26/01/2009 16:10:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tablor
PORTREVISION=	11
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create tables of signs and of variations.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
