# New ports collection makefile for:	texlive-a5comb
# Date created:		13/03/2010 04:38:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	a5comb
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for a5 paper sizes.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
