# New ports collection makefile for:	texlive-euenc
# Date created:		26/01/2009 16:11:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	euenc
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The euenc package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
