# New ports collection makefile for:	texlive-autonum
# Date created:		08/02/2012 12:34:18
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	autonum
PORTVERSION=	20120730
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Automatic equation references.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
