# $FreeBSD$

PORTNAME=	libris
PORTVERSION=	20100713
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Libris ADF fonts, with LaTeX support.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
