# New ports collection makefile for:	texlive-musixflx
# Date created:		13/03/2010 04:55:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	musixflx
PORTVERSION=	20110213
CATEGORIES=	print
DISTFILES=	# None

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The musixflx package

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
