# New ports collection makefile for:	texlive-swebib
# Date created:		26/01/2009 16:06:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	swebib
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Swedish bibliography styles.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
