# $FreeBSD$

PORTNAME=	biblatex-lni
PORTVERSION=	20161016
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LNI style fur BibLaTeX

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
