# New ports collection makefile for:	texlive-t2
# Date created:		26/01/2009 16:05:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	t2
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for using T2 encoding.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
