# New ports collection makefile for:	texlive-supertabular
# Date created:		13/03/2010 04:49:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	supertabular
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A multi-page tables package.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
