# New ports collection makefile for:	texlive-textcase
# Date created:		13/03/2010 04:50:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	textcase
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Case conversion ignoring mathematics, etc.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
