# New ports collection makefile for:	texlive-ctable
# Date created:		13/03/2010 04:53:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ctable
PORTVERSION=	20110418
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Easily typeset centered tables.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
