# $FreeBSD$

PORTNAME=	ctable
PORTVERSION=	20130629
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Flexible typesetting of table and figure floats using key/value directives.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
