# $FreeBSD$

PORTNAME=	l3packages
PORTVERSION=	20151105
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	High-level LaTeX3 concepts

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
