# New ports collection makefile for:	texlive-datatool
# Date created:		13/03/2010 04:40:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	datatool
PORTVERSION=	20120927
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Tools to load and manipulate data.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
