# $FreeBSD$

PORTNAME=	biblatex-bookinarticle
PORTVERSION=	20140703
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Manage book edited in article.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
