# New ports collection makefile for:	texlive-catechis
# Date created:		13/03/2010 04:39:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	catechis
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for typesetting catechisms.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
