# New ports collection makefile for:	texlive-hanoi
# Date created:		01/05/2012 04:46:07
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	hanoi
PORTVERSION=	20120104
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Tower of Hanoi in TeX.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
