# $FreeBSD$

PORTNAME=	phfsvnwatermark
PORTVERSION=	20160817
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Watermarks with version control information from SVN

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
