# New ports collection makefile for:	texlive-adfathesis
# Date created:		04/21/2012 05:11:03
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	adfathesis
PORTVERSION=	20120421
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Australian Defence Force Academy thesis format.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
