# New ports collection makefile for:	texlive-nddiss
# Date created:		13/03/2010 04:58:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nddiss
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Notre Dame Dissertation format class.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
