# $FreeBSD$

PORTNAME=	tikzposter
PORTVERSION=	20121025
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create scientific posters using TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
