# New ports collection makefile for:	texlive-itnumpar
# Date created:		26/01/2009 16:06:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	itnumpar
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Spell numbers in words (Italian).

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
