# New ports collection makefile for:	texlive-staves
# Date created:		26/01/2009 16:04:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	staves
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset Icelandic staves and runic letters. 

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
