# New ports collection makefile for:	texlive-eepic
# Date created:		13/03/2010 04:52:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	eepic
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extensions to epic and the LaTeX drawing tools.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
