# New ports collection makefile for:	texlive-frankenstein
# Date created:		13/03/2010 04:42:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	frankenstein
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of LaTeX packages. 


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
