# New ports collection makefile for:	texlive-xpatch
# Date created:		01/25/2012 05:07:48
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	xpatch
PORTVERSION=	20120125
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extending etoolbox patching commands.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
