# $FreeBSD$

PORTNAME=	libertinus
PORTVERSION=	20160123
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The Libertinus font family

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
