# New ports collection makefile for:	texlive-borceux
# Date created:		13/03/2010 04:31:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	borceux
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Diagram macros by Francois Borceux.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
