# New ports collection makefile for:	texlive-mongolian-babel
# Date created:		13/03/2010 04:37:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mongolian-babel
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A language definition file for Mongolian in Babel.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
