# New ports collection makefile for:	texlive-flagderiv
# Date created:		13/03/2010 04:42:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	flagderiv
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Flag style derivation package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
