# New ports collection makefile for:	texlive-dirtree
# Date created:		13/03/2010 04:31:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dirtree
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Display trees in the style of windows explorer.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
