# New ports collection makefile for:	texlive-musuos
# Date created:		08/24/2011 05:11:18
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	musuos
PORTVERSION=	20110923
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset papers for the department of music, Osnabruck.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
