# New ports collection makefile for:	texlive-lettrine
# Date created:		13/03/2010 04:44:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lettrine
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset dropped capitals.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
