# New ports collection makefile for:	texlive-euproposal
# Date created:		13/03/2010 04:58:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	euproposal
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A class for preparing FP7 proposals.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
