# New ports collection makefile for:	texlive-euproposal
# Date created:		26/01/2009 16:11:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	euproposal
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A class for preparing FP7 proposals.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
