# New ports collection makefile for:	texlive-randomwalk
# Date created:		01/25/2011 04:50:41
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	randomwalk
PORTVERSION=	20110125
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Random walks using TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
