# New ports collection makefile for:	texlive-calculator
# Date created:		08/02/2012 12:34:54
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	calculator
PORTVERSION=	20120724
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use LaTeX as a scientific calculator.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
