# New ports collection makefile for:	texlive-IEEEconf
# Date created:		26/01/2009 16:11:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	IEEEconf
PORTREVISION=	11
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for IEEE conference proceedings.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
