# New ports collection makefile for:	texlive-trimspaces
# Date created:		13/03/2010 04:50:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	trimspaces
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Trim spaces around an argument or within a macro.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
