# New ports collection makefile for:	texlive-chemfig
# Date created:		09/21/2010 11:44:10
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	chemfig
PORTVERSION=	20111223
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw molecules with easy syntax.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
