# New ports collection makefile for:	texlive-engrec
# Date created:		13/03/2010 04:41:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	engrec
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Enumerate with lower- or uppercase Greek letters.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
