# New ports collection makefile for:	texlive-emptypage
# Date created:		13/03/2010 04:41:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	emptypage
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make empty pages really empty.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
