# New ports collection makefile for:	texlive-hexgame
# Date created:		13/03/2010 04:31:06
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hexgame
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Provide an environment to draw a hexgame-board.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
