# New ports collection makefile for:	texlive-statex2
# Date created:		13/03/2010 04:54:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	statex2
PORTVERSION=	20110917
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Statistics style.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
