# New ports collection makefile for:	texlive-tkz-doc
# Date created:		13/03/2010 04:52:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tkz-doc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Documentation macros for the TKZ series of packages.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
