# New ports collection makefile for:	texlive-acro
# Date created:		08/02/2012 12:33:55
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	acro
PORTVERSION=	20120727
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset acronyms.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
