# New ports collection makefile for:	texlive-dyntree
# Date created:		13/03/2010 05:00:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dyntree
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Construct Dynkin tree diagrams.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
