# New ports collection makefile for:	texlive-expressg
# Date created:		13/03/2010 04:22:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	expressg
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Diagrams consisting of boxes, lines, and annotations.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
