# $FreeBSD$

PORTNAME=	bodegraph
PORTVERSION=	20140418
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Bode, Nyquist and Black plots with gnuplot and TikZ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
