# $FreeBSD$

PORTNAME=	graphbox
PORTVERSION=	20140901
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extend graphicx to improve placement of graphics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
