# New ports collection makefile for:	texlive-rcs
# Date created:		13/03/2010 04:54:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	rcs
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Use RCS (revision control system) tags in LaTeX documents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
