# $FreeBSD$

PORTNAME=	placeat
PORTVERSION=	20140419
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The placeat package

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
