# New ports collection makefile for:	texlive-courier
# Date created:		13/03/2010 04:29:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	courier
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Adobe Type 1 "free" copies of Courier.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
