# New ports collection makefile for:	texlive-mapcodes
# Date created:		13/03/2010 04:44:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mapcodes
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for multiple character sets and encodings.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
