# New ports collection makefile for:	texlive-dox
# Date created:		13/03/2010 04:40:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dox
PORTVERSION=	20101217
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extend the doc package.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
