# New ports collection makefile for:	texlive-codepage
# Date created:		13/03/2010 04:39:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	codepage
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for variant code pages.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
