# New ports collection makefile for:	texlive-pdfsync
# Date created:		13/03/2010 04:47:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdfsync
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Provide links between source and PDF.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
