# New ports collection makefile for:	texlive-subfigure
# Date created:		13/03/2010 04:49:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	subfigure
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Deprecated: Figures divided into subfigures.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
