# New ports collection makefile for:	texlive-ncntrsbk
# Date created:		13/03/2010 04:30:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ncntrsbk
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The ncntrsbk package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
