# $FreeBSD$

PORTNAME=	mfpic
PORTVERSION=	20121205
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Metafont/post pictures from (La)TeX commands.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
