# New ports collection makefile for:	texlive-junicode
# Date created:		13/03/2010 04:27:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	junicode
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A TrueType font for mediaevalists.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
