# New ports collection makefile for:	texlive-regcount
# Date created:		13/03/2010 04:48:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	regcount
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Display the allocation status of the TeX registers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
