# New ports collection makefile for:	texlive-directory
# Date created:		26/01/2009 16:07:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	directory
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	An address book using BibTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
