# $FreeBSD$

PORTNAME=	tikz-page
PORTVERSION=	20160830
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Small macro to help building nice and complex layout materials

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
