# New ports collection makefile for:	texlive-lcg
# Date created:		13/03/2010 04:44:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lcg
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate random integers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
