# New ports collection makefile for:	texlive-jura
# Date created:		26/01/2009 16:05:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	jura
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A document class for German legal texts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
