# New ports collection makefile for:	texlive-musixlyr
# Date created:		13/03/2010 04:55:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	musixlyr
PORTVERSION=	20101101
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The musixlyr package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
