# $FreeBSD$

PORTNAME=	ESIEEcv
PORTVERSION=	20100610
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Curriculum vitae for French use.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
