# New ports collection makefile for:	texlive-clefval
# Date created:		26/01/2009 16:07:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	clefval
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Key/value support with a hash.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
