# New ports collection makefile for:	texlive-svn-prov
# Date created:		13/03/2010 04:49:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	svn-prov
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Subversion variants of \Provides... macros.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
