# New ports collection makefile for:	texlive-boondox
# Date created:		05/07/2011 04:53:38
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	boondox
PORTVERSION=	20110507
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Mathematical alphabets derived from the STIX fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
