# New ports collection makefile for:	texlive-mftinc
# Date created:		13/03/2010 04:44:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mftinc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Pretty-print Metafont source.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
