# $FreeBSD$

PORTNAME=	babel-breton
PORTVERSION=	20130506
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The babel-breton package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
