# New ports collection makefile for:	texlive-algorithms
# Date created:		13/03/2010 04:59:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	algorithms
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A suite of tools for typesetting algorithms in pseudo-code.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
