# $FreeBSD$

PORTNAME=	texlive-docindex
PORTVERSION=	20140318
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	top-level TeX Live doc.html, etc.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
