# New ports collection makefile for:	texlive-path
# Date created:		09/23/2010 05:44:49
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	path
PORTVERSION=	20110412
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset paths, making them breakable.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
