# New ports collection makefile for:	texlive-eso-pic
# Date created:		13/03/2010 04:53:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	eso-pic
PORTVERSION=	20101009
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Add picture commands (or backgrounds) to every page.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
