# New ports collection makefile for:	texlive-musixlyr
# Date created:		26/01/2009 16:10:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	musixlyr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	MusiXTeX Extension Package for Lyrics Handling.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
