# New ports collection makefile for:	texlive-pst-math
# Date created:		13/03/2010 04:57:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-math
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Enhancement of PostScript math operators to use with pstricks


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
