# $FreeBSD$

PORTNAME=	pst-tree
PORTVERSION=	20110930
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Trees, using pstricks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
