# $FreeBSD$

PORTNAME=	xcookybooky
PORTVERSION=	20130314
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset (potentially long) recipes.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
