# New ports collection makefile for:	texlive-charter
# Date created:		13/03/2010 04:29:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	charter
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Charter fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
