# $FreeBSD$

PORTNAME=	lkproof
PORTVERSION=	20101009
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LK Proof figure macros.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
