# New ports collection makefile for:	texlive-mtgreek
# Date created:		13/03/2010 04:46:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mtgreek
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Use italic and upright greek letters with mathtime.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
