# New ports collection makefile for:	texlive-titling
# Date created:		26/01/2009 16:09:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	titling
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Control over the typesetting of the \maketitle command.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
