# New ports collection makefile for:	texlive-oldstandard
# Date created:		09/21/2010 11:38:18
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	oldstandard
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Old Standard: A Unicode Font for Classical and Medieval Studies.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
