# New ports collection makefile for:	texlive-babel
# Date created:		26/01/2009 16:02:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	babel
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Multilingual support for Plain TeX or LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
