# New ports collection makefile for:	texlive-struktex
# Date created:		13/03/2010 05:00:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	struktex
PORTVERSION=	20120413
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Nassi-Schneidermann charts


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
