# New ports collection makefile for:	texlive-pst-calendar
# Date created:		13/03/2010 04:56:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-calendar
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Plot calendars in "fancy" ways.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
