# $FreeBSD$

PORTNAME=	crbox
PORTVERSION=	20130407
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Boxes with crossed corners.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
