# New ports collection makefile for:	texlive-crbox
# Date created:		10/29/2011 04:54:46
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	crbox
PORTVERSION=	20111028
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Boxes with crossed corners.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
