# New ports collection makefile for:	texlive-asyfig
# Date created:		13/03/2010 04:51:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	asyfig
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Commands for using Asymptote figures.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
