# $FreeBSD$

PORTNAME=	rviewport
PORTVERSION=	20110829
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Relative Viewport for Graphics Inclusion.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
