# New ports collection makefile for:	texlive-cs
# Date created:		13/03/2010 04:35:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cs
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The cs package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
