# New ports collection makefile for:	texlive-etaremune
# Date created:		13/03/2010 04:42:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	etaremune
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Reverse-counting enumerate environment.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
