# New ports collection makefile for:	texlive-verbatimcopy
# Date created:		13/03/2010 04:51:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	verbatimcopy
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make copies of text documents from within LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
