# $FreeBSD$

PORTNAME=	shadowtext
PORTVERSION=	20120521
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	shadowtext

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
