# New ports collection makefile for:	texlive-metauml
# Date created:		13/03/2010 04:22:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	metauml
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	MetaPost library for typesetting UML diagrams.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
