# $FreeBSD$

PORTNAME=	tkz-tab
PORTVERSION=	20110607
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Tables of signs and variations using PGF/TikZ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
