# $FreeBSD$

PORTNAME=	poemscol
PORTVERSION=	20130804
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typesetting Critical Editions of Poetry.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
