# New ports collection makefile for:	texlive-silence
# Date created:		13/03/2010 04:49:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	silence
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Selective filtering of error messages and warnings.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
