# New ports collection makefile for:	texlive-zhspacing
# Date created:		13/03/2010 04:34:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	zhspacing
PORTVERSION=	20120316
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Spacing for mixed CJK-English documents in XeTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
