# $FreeBSD$

PORTNAME=	eqlist
PORTVERSION=	20131128
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Description lists with equal indentation.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
