# New ports collection makefile for:	texlive-eqlist
# Date created:		26/01/2009 16:07:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	eqlist
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Description lists with equal indentation.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
