# New ports collection makefile for:	texlive-titlesec
# Date created:		13/03/2010 04:50:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	titlesec
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Select alternative section titles.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
