# New ports collection makefile for:	texlive-colordoc
# Date created:		09/21/2010 11:45:58
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	colordoc
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Coloured syntax highlights in documentation.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
