# $FreeBSD$

PORTNAME=	colordoc
PORTVERSION=	20100610
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Coloured syntax highlights in documentation.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
