# New ports collection makefile for:	texlive-newsletr
# Date created:		26/01/2009 16:10:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newsletr
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for making newsletters with Plain TeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
