# $FreeBSD$

PORTNAME=	bagpipe
PORTVERSION=	20140625
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for typesetting bagpipe music.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
