# New ports collection makefile for:	texlive-mafr
# Date created:		13/03/2010 04:35:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mafr
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Mathematics in accord with French usage.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
