# $FreeBSD$

PORTNAME=	xcharter
PORTVERSION=	20160612
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extension of Bitstream Charter fonts

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
