# New ports collection makefile for:	texlive-marigold
# Date created:		13/03/2010 04:28:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	marigold
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The marigold package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
