# New ports collection makefile for:	texlive-easylist
# Date created:		26/01/2009 16:07:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	easylist
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Lists using a single active character.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
