# $FreeBSD$

PORTNAME=	gzt
PORTVERSION=	20170103
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bundle of classes for "La Gazette des Mathematiciens"

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
