# New ports collection makefile for:	texlive-har2nat
# Date created:		13/03/2010 04:58:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	har2nat
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Replace the harvard package with natbib.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
