# $FreeBSD$

PORTNAME=	hausarbeit-jura
PORTVERSION=	20160427
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Class for writing "juristische Hausarbeiten" at German Universities

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
