# New ports collection makefile for:	texlive-plari
# Date created:		13/03/2010 04:32:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	plari
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typesetting stageplay scripts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
