# New ports collection makefile for:	texlive-cmdstring
# Date created:		13/03/2010 04:39:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cmdstring
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Get command name reliably.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
