# New ports collection makefile for:	texlive-altfont
# Date created:		13/03/2010 04:38:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	altfont
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Alternative font handling in LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
