# New ports collection makefile for:	texlive-pinlabel
# Date created:		26/01/2009 16:10:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pinlabel
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A TeX labelling package.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
