# New ports collection makefile for:	texlive-chicago
# Date created:		26/01/2009 16:03:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	chicago
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A "Chicago" bibliography style.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
