# $FreeBSD$

PORTNAME=	endfloat
PORTVERSION=	20111229
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Move floats to the end, leaving markers where they belong.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
