# New ports collection makefile for:	texlive-multibbl
# Date created:		26/01/2009 16:08:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	multibbl
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Multiple bibliographies.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
