# New ports collection makefile for:	texlive-GS1
# Date created:		08/20/2012 05:04:21
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	GS1
PORTVERSION=	20120819
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The GS1 package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
