# $FreeBSD$

PORTNAME=	biblatex-anonymous
PORTVERSION=	20141028
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The biblatex-anonymous package

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
