# New ports collection makefile for:	texlive-figsize
# Date created:		13/03/2010 04:42:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	figsize
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Auto-size graphics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
