# New ports collection makefile for:	texlive-memoir
# Date created:		26/01/2009 16:10:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	memoir
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset fiction, non-fiction and mathematical books.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
