# New ports collection makefile for:	texlive-turkmen
# Date created:		04/11/2010 14:16:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	turkmen
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Babel support for Turkmen.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
