# New ports collection makefile for:	texlive-gcard
# Date created:		26/01/2009 16:08:01
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	gcard
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Arrange text on a sheet to fold into a greeting card.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
