# New ports collection makefile for:	texlive-pdftricks
# Date created:		13/03/2010 04:56:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdftricks
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for pstricks in pdfTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
