# New ports collection makefile for:	texlive-pxfonts
# Date created:		26/01/2009 16:04:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pxfonts
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Palatino-like fonts in support of mathematics.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
