# New ports collection makefile for:	texlive-xetex-def
# Date created:		13/03/2010 05:00:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xetex-def
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Colour and graphics support for XeTeX.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
