# New ports collection makefile for:	texlive-pst-pdgr
# Date created:		13/03/2010 04:57:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-pdgr
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw medical pedigrees using pstricks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
