# $FreeBSD$

PORTNAME=	tikz-cd
PORTVERSION=	20130103
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create commutative diagrams with TikZ

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
