# $FreeBSD$

PORTNAME=	lmake
PORTVERSION=	20120303
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Process lists to do repetitive actions.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
