# New ports collection makefile for:	texlive-trajan
# Date created:		13/03/2010 04:29:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	trajan
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fonts from the Trajan column in Rome.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
