# New ports collection makefile for:	texlive-jsclasses
# Date created:		09/21/2010 11:41:30
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	jsclasses
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Classes tailored for use with Japanese.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
