# New ports collection makefile for:	texlive-sciwordconv
# Date created:		13/03/2010 04:48:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sciwordconv
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Use Scientific Word/WorkPlace files with another TeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
