# New ports collection makefile for:	texlive-xmlplay
# Date created:		13/03/2010 04:32:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xmlplay
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset Shakespeare's plays as marked up by Bosak.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
