# $FreeBSD$

PORTNAME=	glossaries
PORTVERSION=	20121120
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create glossaries and lists of acronyms.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
