# New ports collection makefile for:	texlive-pittetd
# Date created:		26/01/2009 16:08:53
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pittetd
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Electronic Theses and Dissertations at Pitt.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
