# New ports collection makefile for:	texlive-tokenizer
# Date created:		26/01/2009 16:09:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tokenizer
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A tokenizer.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
