# New ports collection makefile for:	texlive-crossreference
# Date created:		13/03/2010 04:40:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	crossreference
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Crossreferences within documents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
