# New ports collection makefile for:	texlive-garuda-c90
# Date created:		26/01/2009 16:05:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	garuda-c90
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The garuda-c90 package

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
