# New ports collection makefile for:	texlive-ibygrk
# Date created:		13/03/2010 04:36:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ibygrk
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fonts and macros to typeset ancient Greek.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
