# New ports collection makefile for:	texlive-makecirc
# Date created:		26/01/2009 16:08:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	makecirc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The makecirc package

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
