# New ports collection makefile for:	texlive-piff
# Date created:		12/11/2010 04:55:34
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	piff
PORTVERSION=	20101211
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macro tools by Mike Piff.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
