# $FreeBSD$

PORTNAME=	mathastext
PORTVERSION=	20130124
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use the text font in simple mathematics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
