# New ports collection makefile for:	texlive-autotab
# Date created:		13/03/2010 04:38:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	autotab
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Generating tabulars from input data.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
