# New ports collection makefile for:	texlive-dprogress
# Date created:		13/03/2010 04:40:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dprogress
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX-relevant log information for debugging.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
