# New ports collection makefile for:	texlive-biblatex-dw
# Date created:		13/03/2010 13:03:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	biblatex-dw
PORTVERSION=	20101123
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Humanities styles for biblatex.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
