# $FreeBSD$

PORTNAME=	cbfonts
PORTVERSION=	20130911
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Complete set of Greek fonts.

RUN_DEPENDS=	${LOCALBASE}/share/texmf-dist/tex/latex/cbfonts-fd/lgrcmr.fd:${PORTSDIR}/print/texlive-cbfonts-fd

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
