# New ports collection makefile for:	texlive-acronym
# Date created:		13/03/2010 04:38:29
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	acronym
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Expand acronyms at least once.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
