# $FreeBSD$

PORTNAME=	rtkinenc
PORTVERSION=	20101006
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Input encoding with fallback procedures.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
