# New ports collection makefile for:	texlive-soul
# Date created:		13/03/2010 04:49:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	soul
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Hyphenation for letterspacing, underlining, and more.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
