# New ports collection makefile for:	texlive-fltpoint
# Date created:		13/03/2010 04:31:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fltpoint
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Simple floating point arithmetic.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
