# New ports collection makefile for:	texlive-curves
# Date created:		26/01/2009 16:10:43
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	curves
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Curves for LaTeX picture environment

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
