# New ports collection makefile for:	texlive-ibycus-babel
# Date created:		13/03/2010 04:36:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ibycus-babel
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use the Ibycus 4 Greek font with Babel


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
