# New ports collection makefile for:	texlive-prettyref
# Date created:		13/03/2010 04:47:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	prettyref
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make label references "self-identify".


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
