# New ports collection makefile for:	texlive-etextools
# Date created:		13/03/2010 04:42:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	etextools
PORTVERSION=	20101211
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	e-TeX tools for LaTeX users and package writers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
