# New ports collection makefile for:	texlive-pst-solides3d
# Date created:		13/03/2010 04:57:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-solides3d
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw perspective views of 3D solids.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
