# New ports collection makefile for:	texlive-serbian-date-lat
# Date created:		08/09/2011 05:02:57
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	serbian-date-lat
PORTVERSION=	20110809
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Updated date typesetting for Serbian.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
