# New ports collection makefile for:	texlive-datenumber
# Date created:		13/03/2010 04:40:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	datenumber
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Convert a date into a number and vice versa.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
