# New ports collection makefile for:	texlive-eukdate
# Date created:		13/03/2010 04:42:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	eukdate
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	UK format dates, with weekday.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
