# $FreeBSD$

PORTNAME=	logicproof
PORTVERSION=	20140322
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The logicproof package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
