# New ports collection makefile for:	texlive-chemstyle
# Date created:		13/03/2010 04:59:56
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	chemstyle
PORTVERSION=	20101106
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Writing chemistry with style.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
