# New ports collection makefile for:	texlive-sfmath
# Date created:		13/03/2010 04:48:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sfmath
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Sans-serif mathematics.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
