# New ports collection makefile for:	texlive-memexsupp
# Date created:		26/01/2009 16:08:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	memexsupp
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Experimental memoir support.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
