# New ports collection makefile for:	texlive-bibhtml
# Date created:		13/03/2010 04:23:03
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bibhtml
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	BibTeX support for HTML files.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
