# New ports collection makefile for:	texlive-c-pascal
# Date created:		13/03/2010 04:31:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	c-pascal
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset Python, C and Pascal programs.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
