# New ports collection makefile for:	texlive-nonumonpart
# Date created:		04/19/2011 04:57:45
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	nonumonpart
PORTVERSION=	20110419
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Prevent page numbers on part pages.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
