# New ports collection makefile for:	texlive-splines
# Date created:		26/01/2009 16:03:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	splines
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	MetaPost macros for drawing cubic spline interpolants.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
