# $FreeBSD$

PORTNAME=	ajl
PORTVERSION=	20140514
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibTeX style for AJL.

OPTIONS_EXCLUDE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
