# New ports collection makefile for:	texlive-lewis
# Date created:		13/03/2010 04:44:13
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	lewis
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Lewis structures.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
