# New ports collection makefile for:	texlive-pbsheet
# Date created:		26/01/2009 16:08:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pbsheet
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Problem sheet class.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
