# $FreeBSD$

PORTNAME=	biblatex-gost
PORTVERSION=	20141130
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Biblatex support for GOST standard bibliographies.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
