# New ports collection makefile for:	texlive-newfile
# Date created:		26/01/2009 16:08:39
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newfile
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	User level management of LaTeX input and output.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
