# New ports collection makefile for:	texlive-nih
# Date created:		26/01/2009 16:11:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	nih
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A class for NIH grant applications.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
