# $FreeBSD$

PORTNAME=	asciilist
PORTVERSION=	20160307
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Environments AsciiList and AsciiDocList for prototyping nested lists in LaTeX.

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
