# New ports collection makefile for:	texlive-pdfslide
# Date created:		26/01/2009 16:08:50
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pdfslide
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Presentation slides using pdftex.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
