# $FreeBSD$

PORTNAME=	hobby
PORTVERSION=	20120904
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	An implementation of Hobby's algorithm for PGF/TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
