# New ports collection makefile for:	texlive-persian-modern
# Date created:		08/29/2011 04:49:12
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	persian-modern
PORTVERSION=	20110829
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The "Persian Modern" family of fonts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
