# New ports collection makefile for:	texlive-lpic
# Date created:		12/25/2010 04:47:14
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	lpic
PORTVERSION=	20101224
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Put LaTeX material over included graphics.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
