# New ports collection makefile for:	texlive-hyplain
# Date created:		26/01/2009 16:10:53
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hyplain
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The hyplain package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
