# New ports collection makefile for:	texlive-bpchem
# Date created:		13/03/2010 04:59:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bpchem
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset chemical names, formulae, etc.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
