# $FreeBSD$

PORTNAME=	stellenbosch
PORTVERSION=	20120224
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Stellenbosch thesis bundle.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
