# $FreeBSD$

PORTNAME=	answers
PORTVERSION=	20140811
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Setting questions (or exercises) and answers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
