# New ports collection makefile for:	texlive-bin-dialog
# Date created:		26/01/2009 16:02:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bin-dialog
CATEGORIES=	print
DISTFILES=	# None

MAINTAINER=	romain@blogreen.org
COMMENT=	The bin-dialog package

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
