# New ports collection makefile for:	texlive-examplep
# Date created:		26/01/2009 16:07:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	examplep
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Verbatim phrases and listings in LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
