# New ports collection makefile for:	texlive-cool
# Date created:		13/03/2010 04:40:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cool
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	COntent-Oriented LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
