# $FreeBSD$

PORTNAME=	hyphen-base
PORTVERSION=	20140629
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The hyphen-base package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
