# New ports collection makefile for:	texlive-tdsfrmath
# Date created:		13/03/2010 04:35:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tdsfrmath
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros for French teachers of mathematics.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
