# $FreeBSD$

PORTNAME=	beamertheme-detlev-cm
PORTVERSION=	20151207
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A beamer theme designed for use in the University of Leeds

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
