# New ports collection makefile for:	texlive-latexdiff
# Date created:		13/03/2010 04:24:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	latexdiff
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Determine and mark up significant differences between latex files.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
