# $FreeBSD$

PORTNAME=	statex
PORTVERSION=	20101105
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Statistics style.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
