# $FreeBSD$

PORTNAME=	heuristica
PORTVERSION=	20140811
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fonts extending Utopia, with LaTeX support files.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
