# New ports collection makefile for:	texlive-context-account
# Date created:		26/01/2009 16:03:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	context-account
PORTREVISION=	11
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A simple accounting package.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
