# New ports collection makefile for:	texlive-multirow
# Date created:		13/03/2010 04:46:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	multirow
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create tabular cells spanning multiple rows.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
