# New ports collection makefile for:	texlive-dpfloat
# Date created:		13/03/2010 04:40:55
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dpfloat
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for double-page floats.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
