# $FreeBSD$

PORTNAME=	historische-zeitschrift
PORTVERSION=	20140724
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Biblatex style for the journal 'Historische Zeitschrift'

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
