# New ports collection makefile for:	texlive-yafoot
# Date created:		26/01/2009 16:10:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	yafoot
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A bundle of miscellaneous footnote packages.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
