# New ports collection makefile for:	texlive-bondgraph
# Date created:		03/12/2011 04:50:15
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	bondgraph
PORTVERSION=	20110310
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Create bond graph figures in LaTeX documents.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
