# New ports collection makefile for:	texlive-minibox
# Date created:		13/03/2010 04:45:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	minibox
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A simple type of box for LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
