# $FreeBSD$

PORTNAME=	sseq
PORTVERSION=	20130907
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typesetting spectral sequence charts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
