# New ports collection makefile for:	texlive-maybemath
# Date created:		26/01/2009 16:08:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	maybemath
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make math bold or italic according to context.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
