# New ports collection makefile for:	texlive-numprint
# Date created:		13/03/2010 04:46:34
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	numprint
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Print numbers with separators and exponent if necessary.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
