# New ports collection makefile for:	texlive-captcont
# Date created:		13/03/2010 04:39:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	captcont
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Retain float number across several floats.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
