# New ports collection makefile for:	texlive-smartref
# Date created:		13/03/2010 04:49:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	smartref
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extend LaTeX's \ref capability.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
