# New ports collection makefile for:	texlive-beamerthemejltree
# Date created:		04/07/2011 05:10:22
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	beamerthemejltree
PORTVERSION=	20110407
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Contributed beamer theme.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
