# New ports collection makefile for:	texlive-ascelike
# Date created:		26/01/2009 16:11:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ascelike
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Bibliography style for the ASCE.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
