# New ports collection makefile for:	texlive-textmerg
# Date created:		26/01/2009 16:09:40
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	textmerg
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Merge text in TeX and LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
