# New ports collection makefile for:	texlive-beameraudience
# Date created:		08/07/2011 04:53:29
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	beameraudience
PORTVERSION=	20110806
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Assembling beamer frames according to audience

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
