# $FreeBSD$

PORTNAME=	conteq
PORTVERSION=	20130528
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset multiline continued equalities.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
