# New ports collection makefile for:	texlive-ksfh_nat
# Date created:		09/28/2011 04:40:41
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	ksfh_nat
PORTVERSION=	20110928
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The ksfh_nat package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
