# $FreeBSD$

PORTNAME=	gincltex
PORTVERSION=	20110906
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Include TeX files as graphics (.tex support for \includegraphics).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
