# New ports collection makefile for:	texlive-splitbib
# Date created:		26/01/2009 16:03:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	splitbib
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Split and reorder your bibliography.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
