# New ports collection makefile for:	texlive-tamefloats
# Date created:		08/10/2012 05:19:28
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	tamefloats
PORTVERSION=	20120809
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Experimentally use \holdinginserts with LaTeX floats.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
