# New ports collection makefile for:	texlive-trsym
# Date created:		26/01/2009 16:09:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	trsym
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Symbols for transformations.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
