# New ports collection makefile for:	texlive-pst-cox
# Date created:		26/01/2009 16:11:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-cox
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Drawing regular complex polytopes with PSTricks.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
