# New ports collection makefile for:	texlive-spotcolor
# Date created:		26/01/2009 16:09:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	spotcolor
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Spot colours for pdfLaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
