# New ports collection makefile for:	texlive-dlfltxb
# Date created:		13/03/2010 04:40:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dlfltxb
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Macros related to "Introdktion til LaTeX".

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
