# New ports collection makefile for:	texlive-iwona
# Date created:		13/03/2010 04:22:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	iwona
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A two-element sans-serif font.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
