# $FreeBSD$

PORTNAME=	xepersian
PORTVERSION=	20131015
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Persian for LaTeX, using XeTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
