# $FreeBSD$

PORTNAME=	pas-crosswords
PORTVERSION=	20131204
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Creating crossword grids, using TikZ.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
