# New ports collection makefile for:	texlive-dtk
# Date created:		13/03/2010 04:41:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dtk
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Document class for the journal of DANTE.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
