# $FreeBSD$

PORTNAME=	pst-labo
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw objects for Chemistry laboratories.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
