# New ports collection makefile for:	texlive-xetexconfig
# Date created:		13/03/2010 04:22:28
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xetexconfig
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Configuration files for XeTeX.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
