# New ports collection makefile for:	texlive-symbol
# Date created:		13/03/2010 04:30:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	symbol
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The symbol package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
