# New ports collection makefile for:	texlive-fundus
# Date created:		13/03/2010 04:42:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fundus
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Providing LaTeX access to various font families.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
