# $FreeBSD$

PORTNAME=	biblatex-ieee
PORTVERSION=	20130210
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Ieee style files for biblatex.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
