# New ports collection makefile for:	texlive-msc
# Date created:		13/03/2010 04:46:01
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	msc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw MSC diagrams.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
