# New ports collection makefile for:	texlive-carlisle
# Date created:		13/03/2010 04:20:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	carlisle
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	David Carlisle's small packages.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
