# New ports collection makefile for:	texlive-hanging
# Date created:		13/03/2010 04:43:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	hanging
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Hanging paragraphs.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
