# New ports collection makefile for:	texlive-listliketab
# Date created:		13/03/2010 04:44:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	listliketab
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset lists as tables.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
