# $FreeBSD$

PORTNAME=	ptex2pdf
PORTVERSION=	20130508
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Convert Japanese TeX documents to PDF.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
