# New ports collection makefile for:	texlive-newverbs
# Date created:		04/11/2010 14:19:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newverbs
PORTVERSION=	20110219
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Define new versions of \verb, including short verb versions.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
