# New ports collection makefile for:	texlive-splines
# Date created:		13/03/2010 04:22:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	splines
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	MetaPost macros for drawing cubic spline interpolants.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
