# New ports collection makefile for:	texlive-smalltableof
# Date created:		26/01/2009 16:09:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	smalltableof
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create listoffigures etc. in a single chapter.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
