# New ports collection makefile for:	texlive-psizzl
# Date created:		13/03/2010 04:30:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	psizzl
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A TeX format for physics papers.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
