# $FreeBSD$

PORTNAME=	xpicture
PORTVERSION=	20130109
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extensions of LaTeX picture drawing.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
