# New ports collection makefile for:	texlive-invoice
# Date created:		10/06/2011 05:09:50
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	invoice
PORTVERSION=	20111005
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate invoices.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
