# $FreeBSD$

PORTNAME=	bagpipe
PORTVERSION=	20140625
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for typesetting bagpipe music.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
