# New ports collection makefile for:	texlive-spie
# Date created:		26/01/2009 16:11:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	spie
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for formatting SPIE Proceedings manuscripts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
