# New ports collection makefile for:	texlive-elsarticle
# Date created:		13/03/2010 04:41:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	elsarticle
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Class for articles for submission to Elsevier journals.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
