# $FreeBSD$

PORTNAME=	substances
PORTVERSION=	20151022
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A database of chemicals

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
