# New ports collection makefile for:	texlive-youngtab
# Date created:		13/03/2010 05:00:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	youngtab
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset Young-Tableaux.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
