# New ports collection makefile for:	texlive-newvbtm
# Date created:		13/03/2010 04:46:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	newvbtm
PORTVERSION=	20110918
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Define your own verbatim-like environment.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
