# New ports collection makefile for:	texlive-breakcites
# Date created:		13/03/2010 04:23:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	breakcites
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Ensure that multiple citations may break at line end.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
