# $FreeBSD$

PORTNAME=	l3kernel
PORTVERSION=	20140618
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX3 programming conventions.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
