# $FreeBSD$

PORTNAME=	gentium-tug
PORTVERSION=	20130715
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Gentium fonts (in two formats) and support files.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
