# $FreeBSD$

PORTNAME=	missaali
PORTVERSION=	20161231
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A late medieval OpenType textura font

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
