# New ports collection makefile for:	texlive-margbib
# Date created:		26/01/2009 16:03:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	margbib
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Display bibitem tags in the margins.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
