# New ports collection makefile for:	texlive-pst-dbicons
# Date created:		13/03/2010 04:56:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-dbicons
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for drawing ER diagrams.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
