# New ports collection makefile for:	texlive-twoup
# Date created:		13/03/2010 04:50:49
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	twoup
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Print two virtual pages on each physical page.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
