# New ports collection makefile for:	texlive-aiaa
# Date created:		26/01/2009 16:11:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	aiaa
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset AIAA conference papers.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
