# New ports collection makefile for:	texlive-dk-bib
# Date created:		13/03/2010 04:23:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dk-bib
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Danish variants of standard BibTeX styles.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
