# New ports collection makefile for:	texlive-statex2
# Date created:		26/01/2009 16:10:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	statex2
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Statistics style.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
