# $FreeBSD$

PORTNAME=	oldstandard
PORTVERSION=	20160720
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Old Standard: A Unicode Font for Classical and Medieval Studies

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
