# New ports collection makefile for:	texlive-ly1
# Date created:		26/01/2009 16:04:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ly1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for LY1 LaTeX encoding.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
