# $FreeBSD$

PORTNAME=	xebaposter
PORTVERSION=	20160212
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Creates beautiful scientific Persian/Latin posters using TikZ

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
