# New ports collection makefile for:	texlive-psbao
# Date created:		13/03/2010 04:56:03
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	psbao
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw Bao diagrams.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
