# New ports collection makefile for:	texlive-gitinfo
# Date created:		09/05/2011 05:19:27
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	gitinfo
PORTVERSION=	20110905
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Access metadata from the git distributed version control system.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
