# New ports collection makefile for:	texlive-texilikecover
# Date created:		13/03/2010 04:59:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	texilikecover
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A cover-page package, like TeXinfo.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
