# New ports collection makefile for:	texlive-csquotes
# Date created:		26/01/2009 16:07:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	csquotes
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Context sensitive quotation facilities.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
