# New ports collection makefile for:	texlive-mnsymbol
# Date created:		26/01/2009 16:04:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mnsymbol
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Mathematical symbol font for Adobe MinionPro.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
