# New ports collection makefile for:	texlive-dialogl
# Date created:		26/01/2009 16:07:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dialogl
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Macros for constructing interactive LaTeX scripts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
