# New ports collection makefile for:	texlive-qcm
# Date created:		13/03/2010 04:47:47
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	qcm
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A LaTeX2e class for making multiple choice questionnaires


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
