# New ports collection makefile for:	texlive-antt
# Date created:		26/01/2009 16:03:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	antt
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Antykwa Toruńska: a Type 1 family of a Polish traditional type.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
