# $FreeBSD$

PORTNAME=	amsfonts
PORTVERSION=	20130223
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	TeX fonts from the American Mathematical Society.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
