# New ports collection makefile for:	texlive-vita
# Date created:		13/03/2010 04:51:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	vita
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Configurable class for curricula vitarum.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
