# $FreeBSD$

PORTNAME=	alegreya
PORTVERSION=	20151023
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Alegreya fonts with LaTeX support

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
