# New ports collection makefile for:	texlive-piechartmp
# Date created:		26/01/2009 16:03:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	piechartmp
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw pie-charts using MetaPost.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
