# New ports collection makefile for:	texlive-duerer-latex
# Date created:		13/03/2010 04:26:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	duerer-latex
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX support for the Duerer fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
