# New ports collection makefile for:	texlive-iopart-num
# Date created:		13/03/2010 04:23:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	iopart-num
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Numeric citation style for IOP journals.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
