# New ports collection makefile for:	texlive-isotope
# Date created:		13/03/2010 04:43:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	isotope
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A package for type setting isotopes

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
