# New ports collection makefile for:	texlive-sugconf
# Date created:		13/03/2010 04:59:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	sugconf
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	SAS(R) user group conference proceedings document class.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
