# New ports collection makefile for:	texlive-AkkTeX
# Date created:		26/01/2009 16:06:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	AkkTeX
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of packages and classes.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
