# New ports collection makefile for:	texlive-mapcodes
# Date created:		26/01/2009 16:08:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mapcodes
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for multiple character sets and encodings.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
