# New ports collection makefile for:	texlive-linearA
# Date created:		13/03/2010 04:28:33
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	linearA
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Linear A script fonts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
