# New ports collection makefile for:	texlive-pitex
# Date created:		09/21/2010 11:54:43
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	pitex
PORTVERSION=	20111204
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Documentation macros.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
