# New ports collection makefile for:	texlive-stage
# Date created:		26/01/2009 16:05:32
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	stage
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A LaTeX class for stage plays

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
