# $FreeBSD$

PORTNAME=	figbas
PORTVERSION=	20130126
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Mini-fonts for figured-bass notation in music.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
