# New ports collection makefile for:	texlive-cm-lgc
# Date created:		26/01/2009 16:04:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cm-lgc
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Type 1 CM-based fonts for Latin, Greek and Cyrillic.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
