# New ports collection makefile for:	texlive-xetexfontinfo
# Date created:		26/01/2009 16:12:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xetexfontinfo
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Report font features in XeTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
