# $FreeBSD$

PORTNAME=	tablestyles
PORTVERSION=	20140702
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The tablestyles package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
