# New ports collection makefile for:	texlive-adrconv
# Date created:		13/03/2010 04:38:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	adrconv
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	BibTeX styles to implement an address database.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
