# New ports collection makefile for:	texlive-genmisc
# Date created:		26/01/2009 16:05:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	genmisc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The genmisc package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
