# New ports collection makefile for:	texlive-labelcas
# Date created:		13/03/2010 04:44:02
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	labelcas
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Check the existence of labels, and fork accordingly.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
