# New ports collection makefile for:	texlive-colorwav
# Date created:		26/01/2009 16:07:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	colorwav
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Colours by wavelength of visible light.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
