# $FreeBSD$

PORTNAME=	biblatex-abnt
PORTVERSION=	20160513
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibLaTeX style for Brazil's ABNT rules

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
