# New ports collection makefile for:	texlive-dozenal
# Date created:		13/03/2010 04:26:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dozenal
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset documents using base twelve numbering (also called "dozenal")


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
