# New ports collection makefile for:	texlive-sepfootnotes
# Date created:		03/08/2012 05:05:26
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	sepfootnotes
PORTVERSION=	20120308
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Define the texts of footnotes defined before their marks.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
