# New ports collection makefile for:	texlive-figbas
# Date created:		13/03/2010 04:55:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	figbas
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Mini-fonts for figured-bass notation in music.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
