# New ports collection makefile for:	texlive-bitelist
# Date created:		03/31/2012 04:46:47
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	bitelist
PORTVERSION=	20120331
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Split list, in TeX's mouth.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
