# $FreeBSD$

PORTNAME=	insbox
PORTVERSION=	20140619
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Insert pictures/boxes into paragraphs.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
