# $FreeBSD$

PORTNAME=	rmathbr
PORTVERSION=	20150615
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Repeating of math operator at the broken line and the new line in inline equations

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
