# New ports collection makefile for:	texlive-dateiliste
# Date created:		26/01/2009 16:07:15
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dateiliste
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Extensions of the \listfiles concept.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
