# $FreeBSD$

PORTNAME=	table-fct
PORTVERSION=	20160815
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw a variations table of functions and a convexity table of its graph.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
