# $FreeBSD$

PORTNAME=	banglatex
PORTVERSION=	20161021
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Enhanced LaTeX integration for Bangla

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
