# New ports collection makefile for:	texlive-fix2col
# Date created:		13/03/2010 04:20:23
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fix2col
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fix miscellaneous two column mode features.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
