# New ports collection makefile for:	texlive-statex
# Date created:		11/05/2010 05:03:52
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	statex
PORTVERSION=	20101105
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Statistics style.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
