# New ports collection makefile for:	texlive-seuthesis
# Date created:		04/11/2010 14:24:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	seuthesis
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX template for theses at Southeastern University.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
