# New ports collection makefile for:	texlive-xbmc
# Date created:		13/03/2010 04:51:34
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	xbmc
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The xbmc package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
