# New ports collection makefile for:	texlive-isodate
# Date created:		26/01/2009 16:08:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	isodate
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Tune the output format of dates according to language.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
