# New ports collection makefile for:	texlive-cweb
# Date created:		13/03/2010 04:23:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	cweb
PORTVERSION=	20110427
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A Web system in C.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
