# New ports collection makefile for:	texlive-bophook
# Date created:		13/03/2010 04:39:09
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bophook
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Provides an At-Begin-Page hook.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
