# $FreeBSD$

PORTNAME=	yathesis
PORTVERSION=	20141004
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	yathesis provides a LaTeX class that aims to help to write a thesis following French rules


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
