# New ports collection makefile for:	texlive-fbs
# Date created:		13/03/2010 04:23:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fbs
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	BibTeX style for Frontiers in Bioscience.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
