# $FreeBSD$

PORTNAME=	fixocgx
PORTVERSION=	20150616
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Add support for dvips+ps2pdf, XeLaTeX, dvipdfmx to the ocgx package.

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
