# $FreeBSD$

PORTNAME=	isomath
PORTVERSION=	20120913
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Mathematics style for science and technology.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
