# New ports collection makefile for:	texlive-ncctools
# Date created:		13/03/2010 04:46:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ncctools
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of general packages for LaTeX


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
