# New ports collection makefile for:	texlive-makecell
# Date created:		13/03/2010 04:44:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	makecell
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Tabular column heads and multilined cells.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
