# New ports collection makefile for:	texlive-fragments
# Date created:		13/03/2010 04:42:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fragments
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Fragments of LaTeX code.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
