# New ports collection makefile for:	texlive-mhequ
# Date created:		13/03/2010 04:54:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mhequ
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Multicolumn equations, tags, labels, sub-numbering.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
