# New ports collection makefile for:	texlive-catcodes
# Date created:		09/23/2012 05:11:31
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	catcodes
PORTVERSION=	20120922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	The catcodes package


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
