# New ports collection makefile for:	texlive-schemabloc
# Date created:		13/03/2010 04:52:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	schemabloc
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Draw block diagrams, using Tikz.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
