# New ports collection makefile for:	texlive-pst-grad
# Date created:		13/03/2010 04:56:55
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-grad
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Filling with colour gradients, using PStricks.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
