# New ports collection makefile for:	texlive-trajan
# Date created:		26/01/2009 16:04:42
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	trajan
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Fonts from the Trajan column in Rome.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
