# $FreeBSD$

PORTNAME=	noconflict
PORTVERSION=	20130428
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Resolve macro name conflict between packages.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
