# New ports collection makefile for:	texlive-fpl
# Date created:		13/03/2010 04:30:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fpl
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	SC and OsF fonts for URW Palladio L


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
