# New ports collection makefile for:	texlive-psbao
# Date created:		26/01/2009 16:10:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	psbao
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Draw Bao diagrams.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
