# New ports collection makefile for:	texlive-unitsdef
# Date created:		13/03/2010 05:00:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	unitsdef
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typesetting units in LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
