# $FreeBSD$

PORTNAME=	biblatex-swiss-legal
PORTVERSION=	20140122
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bibliography and citation styles following Swiss legal practice.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
