# New ports collection makefile for:	texlive-version
# Date created:		13/03/2010 04:51:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	version
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Conditionally include text.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
