# New ports collection makefile for:	texlive-comment
# Date created:		13/03/2010 04:40:06
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	comment
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Selectively include/excludes portions of text.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
