# New ports collection makefile for:	texlive-dingbat
# Date created:		26/01/2009 16:04:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dingbat
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Two dingbat symbol fonts.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
