# $FreeBSD$

PORTNAME=	tasks
PORTVERSION=	20140731
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Horizontally columned lists.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
