# New ports collection makefile for:	texlive-adhocfilelist
# Date created:		10/22/2012 05:22:58
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	adhocfilelist
PORTVERSION=	20121124
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	'\listfiles' entries from the command line.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
