# New ports collection makefile for:	texlive-bosisio
# Date created:		13/03/2010 04:54:22
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bosisio
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of packages by Francesco Bosisio.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
