# New ports collection makefile for:	texlive-yhmath
# Date created:		13/03/2010 04:55:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	yhmath
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extended maths fonts for LaTeX.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
