# New ports collection makefile for:	texlive-biblatex-science
# Date created:		13/03/2010 04:23:12
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	biblatex-science
PORTVERSION=	20120818
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Biblatex implementation of the Science bibliography style.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
