# New ports collection makefile for:	texlive-semaphor
# Date created:		13/03/2010 04:29:05
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	semaphor
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Semaphore alphabet font.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
