# New ports collection makefile for:	texlive-underlin
# Date created:		13/03/2010 04:51:00
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	underlin
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Underlined running heads.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
