# New ports collection makefile for:	texlive-dinbrief
# Date created:		13/03/2010 04:40:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	dinbrief
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	German letter DIN style.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
