# New ports collection makefile for:	texlive-bracketkey
# Date created:		13/03/2010 04:39:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bracketkey
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Produce bracketed identification keys.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
