# New ports collection makefile for:	texlive-calrsfs
# Date created:		13/03/2010 04:39:18
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	calrsfs
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Copperplate calligraphic letters in LaTeX.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
