# New ports collection makefile for:	texlive-polyglossia-kannada
# Date created:		07/27/2011 04:49:46
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	polyglossia-kannada
PORTVERSION=	20110727
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Kannada support for users of polyglossia.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
