# $FreeBSD$

PORTNAME=	datetime2-greek
PORTVERSION=	20150402
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Greek language module for the datetime2 package.

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
