# New ports collection makefile for:	texlive-germbib
# Date created:		26/01/2009 16:06:07
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	germbib
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	German variants of standard BibTeX styles.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
