# New ports collection makefile for:	texlive-csvtools
# Date created:		13/03/2010 04:40:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	csvtools
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Reading data from CSV files.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
