# New ports collection makefile for:	texlive-jhep
# Date created:		26/01/2009 16:11:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	jhep
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	JHEP style.

LSE_LZMA=	yes
NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
