# New ports collection makefile for:	texlive-footbib
# Date created:		13/03/2010 04:23:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	footbib
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bibliographic references as footnotes.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
