# New ports collection makefile for:	texlive-wasysym
# Date created:		13/03/2010 04:30:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	wasysym
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX support file to use the WASY2 fonts


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
