# $FreeBSD$

PORTNAME=	pedigree-perl
PORTVERSION=	20120515
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Generate TeX pedigree files from CSV files.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
