# New ports collection makefile for:	texlive-vertbars
# Date created:		13/03/2010 04:51:16
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	vertbars
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Mark vertical rules in margin of text.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
