# New ports collection makefile for:	texlive-lualatex-math
# Date created:		05/10/2011 05:04:55
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	lualatex-math
PORTVERSION=	20121028
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Fixes for mathematics-related LuaLaTeX issues.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
