# New ports collection makefile for:	texlive-pst-optexp
# Date created:		26/01/2009 16:11:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-optexp
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Drawing optical experimental setups.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
