# New ports collection makefile for:	texlive-urwchancal
# Date created:		03/12/2011 04:44:03
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	urwchancal
PORTVERSION=	20110312
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Use URW's clone of Zapf Chancery as a maths alphabet.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
