# $FreeBSD$

PORTNAME=	aurl
PORTVERSION=	20160815
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Extends the hyperref package with a mechanism for hyperlinked URLs abbreviated with prefixes

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
