# New ports collection makefile for:	texlive-coursepaper
# Date created:		26/01/2009 16:07:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	coursepaper
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Prepare university course papers.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
