# New ports collection makefile for:	texlive-ctib
# Date created:		26/01/2009 16:06:37
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ctib
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The ctib package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
