# $FreeBSD$

PORTNAME=	lxfonts
PORTVERSION=	20130919
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Set of slide fonts based on CM.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
