# New ports collection makefile for:	texlive-popupmenu
# Date created:		13/03/2010 04:47:26
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	popupmenu
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Create popup menus in PDF files.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
