# $FreeBSD$

PORTNAME=	pythonhighlight
PORTVERSION=	20170211
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Highlighting of Python code, based on the listings package

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
