# New ports collection makefile for:	texlive-inlinebib
# Date created:		13/03/2010 04:23:35
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	inlinebib
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Citations in footnotes.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
