# $FreeBSD$

PORTNAME=	nwejm
PORTVERSION=	20170107
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support for the journal "North-Western European Journal of Mathematics"

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
