# New ports collection makefile for:	texlive-bin-psutils
# Date created:		26/01/2009 16:11:20
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bin-psutils
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	PostScript utilities.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
