# New ports collection makefile for:	texlive-metaplot
# Date created:		13/03/2010 04:22:11
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	metaplot
PORTVERSION=	20100921
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Plot-manipulation macros for use in Metapost.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
