# New ports collection makefile for:	texlive-capt-of
# Date created:		13/03/2010 04:39:21
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	capt-of
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Captions on more than floats.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
