# $FreeBSD$

PORTNAME=	mbenotes
PORTVERSION=	20131003
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Notes in tables or images.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
