# New ports collection makefile for:	texlive-digiconfigs
# Date created:		26/01/2009 16:11:48
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	digiconfigs
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Writing "configurations"

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
