# New ports collection makefile for:	texlive-chappg
# Date created:		13/03/2010 04:39:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	chappg
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Page numbering by chapter.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
