# $FreeBSD$

PORTNAME=	petri-nets
PORTVERSION=	20110926
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A set TeX/LaTeX packages for drawing Petri nets.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
