# New ports collection makefile for:	texlive-varwidth
# Date created:		13/03/2010 04:51:10
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	varwidth
PORTVERSION=	20110928
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A variable-width minipage.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
