# New ports collection makefile for:	texlive-thmbox
# Date created:		13/03/2010 04:55:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	thmbox
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Decorate theorem statements.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
