# New ports collection makefile for:	texlive-ptext
# Date created:		11/02/2012 05:24:38
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	ptext
PORTVERSION=	20121031
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A 'lipsum' for Persian.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
