# New ports collection makefile for:	texlive-mathcomp
# Date created:		13/03/2010 04:54:36
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mathcomp
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Text symbols in maths mode.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
