# New ports collection makefile for:	texlive-stack
# Date created:		26/01/2009 16:09:24
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	stack
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Tools to define and use stacks.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
