# New ports collection makefile for:	texlive-geometry
# Date created:		26/01/2009 16:02:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	geometry
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Flexible and complete interface to document dimensions.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
