# $FreeBSD$

PORTNAME=	grundgesetze
PORTVERSION=	20140627
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset Frege's Grundgesetze der Arithmetik


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
