# $FreeBSD$

PORTNAME=	xgreek
PORTVERSION=	20130712
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	XeLaTeX package for typesetting Greek language documents (beta release).


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
