# New ports collection makefile for:	texlive-mdwtools
# Date created:		26/01/2009 16:10:17
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	mdwtools
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Miscellaneous tools by Mark Wooding.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
