# $FreeBSD$

PORTNAME=	eco
PORTVERSION=	20130312
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Oldstyle numerals using EC fonts.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
