# $FreeBSD$

PORTNAME=	oplotsymbl
PORTVERSION=	20170122
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	some symbols, which are not easily available

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
