# New ports collection makefile for:	texlive-chbibref
# Date created:		13/03/2010 04:23:19
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	chbibref
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Change the Bibliography/References title.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
