# New ports collection makefile for:	texlive-Asana-Math
# Date created:		26/01/2009 16:03:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	Asana-Math
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The Asana-Math package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
