# $FreeBSD$

PORTNAME=	tikzsymbols
PORTVERSION=	20130216
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Some symbols created using TikZ.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
