# $FreeBSD$

PORTNAME=	babel-japanese
PORTVERSION=	20161218
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Babel support for Japanese

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
