# $FreeBSD$

PORTNAME=	texinfo
PORTVERSION=	20130922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Texinfo documentation system.

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
