# $FreeBSD$

PORTNAME=	bidi-atbegshi
PORTVERSION=	20140912
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Bidi-aware shipout macros.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
