# $FreeBSD$

PORTNAME=	fonts-tlwg
PORTVERSION=	20130216
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Thai fonts for LaTeX from TLWG.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
