# New ports collection makefile for:	texlive-tap
# Date created:		13/03/2010 04:37:54
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tap
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	TeX macros for typesetting complex tables.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
