# New ports collection makefile for:	texlive-rtkinenc
# Date created:		26/01/2009 16:09:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	rtkinenc
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Input encoding with fallback procedures.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
