# New ports collection makefile for:	texlive-polynomial
# Date created:		26/01/2009 16:08:55
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	polynomial
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset (univariate) polynomials.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
