# $FreeBSD$

PORTNAME=	mxedruli
PORTVERSION=	20130419
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A pair of fonts for different Georgian alphabets.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
