# New ports collection makefile for:	texlive-upmethodology
# Date created:		13/03/2010 04:51:04
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	upmethodology
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Writing specification such as for UP-based methodologies.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
