# New ports collection makefile for:	texlive-fonttable
# Date created:		13/03/2010 04:42:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fonttable
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Print font tables from a LaTeX document.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
