# $FreeBSD$

PORTNAME=	apnum
PORTVERSION=	20160104
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Arbitrary precision numbers implemented by TeX macros

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
