# $FreeBSD$

PORTNAME=	fdsymbol
PORTVERSION=	20120530
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A maths symbol font.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
