# New ports collection makefile for:	texlive-pst-grad
# Date created:		26/01/2009 16:11:08
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-grad
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Filling with colour gradients, using PStricks.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
