# New ports collection makefile for:	texlive-emp
# Date created:		13/03/2010 04:21:57
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	emp
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	"Encapsulate" MetaPost figures in a document.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
