# New ports collection makefile for:	texlive-hrefhide
# Date created:		09/21/2010 11:48:02
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	hrefhide
PORTVERSION=	20100922
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Suppress hyper links when printing.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
