# $FreeBSD$

PORTNAME=	impnattypo
PORTVERSION=	20130703
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Support typography of l'Imprimerie Nationale FranASSaise.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
