# New ports collection makefile for:	texlive-yfonts
# Date created:		26/01/2009 16:04:44
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	yfonts
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for old German fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
