# New ports collection makefile for:	texlive-syntrace
# Date created:		13/03/2010 04:49:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	syntrace
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Labels for tracing in a syntax tree.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
