# New ports collection makefile for:	texlive-IEEEtran
# Date created:		13/03/2010 04:57:55
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	IEEEtran
PORTVERSION=	20130103
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Document class for IEEE Transactions journals and conferences.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
