# $FreeBSD$

PORTNAME=	keyfloat
PORTVERSION=	20170211
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	provides a key/value interface for generating floats

OPTIONS_DEFINE=	DOCS SRCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
