# New ports collection makefile for:	texlive-ccfonts
# Date created:		26/01/2009 16:10:25
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ccfonts
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Support for Concrete text and math fonts in LaTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
