# New ports collection makefile for:	texlive-antiqua
# Date created:		26/01/2009 16:03:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	antiqua
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The antiqua package

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
