# New ports collection makefile for:	texlive-showcharinbox
# Date created:		08/02/2012 12:44:36
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	showcharinbox
PORTVERSION=	20120716
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Show characters inside a box.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
