# New ports collection makefile for:	texlive-pst-barcode
# Date created:		13/03/2010 04:56:14
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pst-barcode
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Print barcodes using PostScript.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
