# New ports collection makefile for:	texlive-issuulinks
# Date created:		03/01/2012 05:04:50
# Whom:		romain@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	issuulinks
PORTVERSION=	20120327
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Produce external links instead of internal ones.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
