# New ports collection makefile for:	texlive-manfnt
# Date created:		13/03/2010 04:44:41
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	manfnt
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	LaTeX support for the TeX book symbols.

NOPORTDOCS=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
