# $FreeBSD$

PORTNAME=	stanli
PORTVERSION=	20161222
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	TikZ Library for Structural Analysis

OPTIONS_DEFINE=	DOCS
.include <bsd.port.options.mk>

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
