# $FreeBSD$

PORTNAME=	phonrule
PORTVERSION=	20131023
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Typeset linear phonological rules.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
