# New ports collection makefile for:	texlive-kpfonts
# Date created:		26/01/2009 16:04:31
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	kpfonts
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A complete set of fonts for text and mathematics.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
