# New ports collection makefile for:	texlive-glyphlist
# Date created:		26/01/2009 16:02:46
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	glyphlist
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The glyphlist package

NOPORTDOCS=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
