# $FreeBSD$

PORTNAME=	cinzel
PORTVERSION=	20140401
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX support for Cinzel and Cinzel Decorative fonts.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
