# New ports collection makefile for:	texlive-texconfig
# Date created:		13/03/2010 04:19:58
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	texconfig
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	The texconfig package

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
