# New ports collection makefile for:	texlive-pracjourn
# Date created:		26/01/2009 16:11:34
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	pracjourn
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset articles for PracTeX.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
