# New ports collection makefile for:	texlive-fancynum
# Date created:		26/01/2009 16:07:51
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	fancynum
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset numbers.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
