# $FreeBSD$

PORTNAME=	texshade
PORTVERSION=	20111202
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Package for setting nucleotide and peptide alignments.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
