# New ports collection makefile for:	texlive-tocbibind
# Date created:		13/03/2010 04:50:30
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	tocbibind
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Add bibliography/index/contents to Table of Contents.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
