# New ports collection makefile for:	texlive-ncctools
# Date created:		26/01/2009 16:08:38
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	ncctools
PORTREVISION=	1
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	A collection of general packages for LaTeX

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
