# New ports collection makefile for:	texlive-alg
# Date created:		13/03/2010 04:59:45
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	alg
PORTVERSION=	20100610
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	LaTeX environments for typesetting algorithms.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
