# New ports collection makefile for:	texlive-bizcard
# Date created:		13/03/2010 04:38:59
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	bizcard
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Typeset business cards.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
