# New ports collection makefile for:	texlive-titlepic
# Date created:		13/03/2010 04:50:27
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	titlepic
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Add picture to title page of a document.

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
