# New ports collection makefile for:	texlive-a2ping
# Date created:		13/03/2010 04:23:52
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	a2ping
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Advanced PS, PDF, EPS converter.

RUN_DEPENDS=	${LOCALBASE}/bin/tex:${PORTSDIR}/print/texlive-core

NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
