# $FreeBSD$

PORTNAME=	romansh
PORTVERSION=	20120414
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Babel/Polyglossia support for the Romansh language.


.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
