# New ports collection makefile for:	texlive-emptypage
# Date created:		26/01/2009 16:07:40
# Whom:		romain@blogreen.org
#
# $FreeBSD$
#

PORTNAME=	emptypage
PORTREVISION=	2
CATEGORIES=	print

MAINTAINER=	romain@blogreen.org
COMMENT=	Make empty pages really empty.

LSE_LZMA=	yes
NOPORTSRC=	yes

.include "${.CURDIR}/../../print/texlive-core/bsd.texlive.mk"
.include <bsd.port.mk>
